### ISSUE TITLE
SessionSecurityFilterOrderProvider should be in security instead of security-session

### ISSUE THREAD

**Issue by sdelamo** [micronaut-projects/micronaut-security#1]
`SessionSecurityFilterOrderProvider` should be in `security` annotated with `@Requires(beans = {HttpSessionFilter.class})` with a compileOnly dependency to `session` instead of inside the `security-session` module. 

it will achieve correct filter order even if the user is not including the `security-session` module.

**Comment by jameskleeh** [comment]
This was resolved with https://github.com/micronaut-projects/micronaut-security/blame/d54b57ba52df9ae05068593d3c0c1966ce5d0050/security/src/main/java/io/micronaut/security/filters/SessionSecurityFilterOrderProvider.java
