### ISSUE TITLE
how I can use OAuth2 server

### ISSUE THREAD

**Issue by HelloTo4x** [micronaut-projects/micronaut-security#1013]
### Issue description

Hi, how can i use OAuth2 server with Micronaut security, maybe it doesn't support

**Comment by sdelamo** [comment]
Yes, we support it. 

We have many steps by steps tutorials. 

See `Micronaut Security` section in [Micronaut Guides](https://micronaut.io/guides/)

see also [Micronaut Security OAuth 2.0 documetnation](https://micronaut-projects.github.io/micronaut-security/latest/guide/#oauth)
