### ISSUE TITLE
OIDC Azure provider - There are no any groups in response

### ISSUE THREAD

**Issue by vutkin** [micronaut-projects/micronaut-security#1081]
### Expected Behavior

If some user in Azure AD has 150+ groups in response (included subgroups) there will be no any groups, and Azure expects that application will do a second separate request to GraphQL request for groups only.

Like dex do for ex. https://dexidp.io/docs/connectors/microsoft/

### Actual Behaviour

Works well when number of Azure AD groups for user is less than JWT/SAML limit

### Steps To Reproduce

<img width="681" alt="image" src="https://user-images.githubusercontent.com/25753488/186107413-8bbb1cb8-54b2-4749-88e5-31a7cb7c86b6.png">

Ref: https://docs.microsoft.com/en-gb/azure/active-directory/hybrid/how-to-connect-fed-group-claims

Example:

DEBUG in application: Body: {"providerType":"OIDC","providerName":"azuread","username":"testUser@domain.com"}

### Environment Information

JDK: openjdk-11
OS: registry.access.redhat.com/ubi8/openjdk-11:1.13

### Example Application

https://github.com/tchiotludo/akhq

### Version

0.21.0

**Comment by vutkin** [comment]
Any update?

**Comment by sdelamo** [comment]
@vutkin I think you are going to need to provide a replacement and do this extra request.

**Comment by vutkin** [comment]
Switched to DEX IDP.
