### ISSUE TITLE
OpenIdAuthenticationMapper will not put custom claims in the JWT token returned to the browser.

### ISSUE THREAD

**Issue by LPalmerMSI** [micronaut-projects/micronaut-security#1102]
The OpenIdAuthenticationMapper will not put custom attributes or roles in the JWT token returned to the client.  It will only place the original claims and roles provided by the OpenIdTokenResponse.

The OpenIdAuthentactionMapper is being instantiated and createAuthenticationResponse method is being called but the returned token seems to strip away any custom claims or roles. Only those which were originally provided by the provider (in this case keycloak) are being returned to the client.  

### Steps to Reproduce

1. Configure Security using the idtoken authentication method and configure an OpenId provider like keycloak
2. Create an OpenIdAuthenticationMapper implementation that adds custom attributes to the authentication response.
3. Return the idToken, authToken and refreshToken in the response along with a custom attribute.
4. The custom attribute will not be encoded in the JWT token returned to the client. 

### Expected Behaviour

When returning AuthenticationResponse.success(name, roles, attributes) all roles and attributes outlined in the return will be encoded into the JWT token and returned to the client. 

### Actual Behaviour

Any custom attributes are not being encoded in the JWT token returned to the client. 

### Environment Information

- Windows 11 (IntelliJ)
- Micronaut 3.7.0
- JDK 11

Sample Project:

https://github.com/LPalmerMSI/micronaut-openid-problem

**Comment by sdelamo** [comment]
In your sample application, you are using `idtoken` as the value for `micronaut.security.authentication`.  When you do that, we use the ID token directly passed from the authentication server and save it in a cookie. We cannot modify that token payload. It is signed by the authorization server.  The advantage is that you don't need to add any configuration necessary to sign a new token in your app.  When you [set `idtoken` we register beans of type `IdTokenHandler` and `JwtCookieClearerLogoutHandler`](https://micronaut-projects.github.io/micronaut-security/latest/guide/#loginHandler).

However, if you want take ID token, add additional claims create an new token and sign it you should use `cookie` as the value of `micronaut.security.authentication`. Moreover, you will need to[ sign the JWT](https://micronaut-projects.github.io/micronaut-security/latest/guide/#jwtGeneratorSignature). 

Moreover, I see in you sample app that you want to include the original access token refresh etc in the new token. We have configuration to do that. But you have to enable it: 

see [AdditionalClaimsConfigurationProperties](https://micronaut-projects.github.io/micronaut-security/latest/guide/configurationreference.html):

- `micronaut.security.oauth2.openid.additional-claims.jwt`
- `micronaut.security.oauth2.openid.additional-claims.access-token`
- `micronaut.security.oauth2.openid.additional-claims.refresh-token`

**Comment by sdelamo** [comment]
@LPalmerMSI I am going to close this issue since I believe it is not a bug. Let me know if you need any extra help.
