### ISSUE TITLE
Use new session module in security

### ISSUE THREAD

**Issue by sdelamo** [micronaut-projects/micronaut-security#1156]
### Issue description

https://github.com/micronaut-projects/micronaut-session

**Comment by timyates** [comment]
I guess this should come after you merge 3.8 in https://github.com/micronaut-projects/micronaut-security/pull/1147 to avoid more of the same?

**Comment by sdelamo** [comment]
> I guess this should come after you merge 3.9 in #1147 to avoid more of the same?

Yup

**Comment by sdelamo** [comment]
I think you can do this already.
