### ISSUE TITLE
LoginFailedEvent doesn't know the user who tries to login

### ISSUE THREAD

**Issue by HelLViS69** [micronaut-projects/micronaut-security#1188]
It would be nice if LoginFailedEvent (or even AuthenticationResponse) carries the username who failed the login.
The following snippet doesn't work as expected because `source.getAuthentication()` is empty

```
@Slf4j
@Singleton
public class LoginFailedEventListener implements ApplicationEventListener<LoginFailedEvent> {

	@Override
	public void onApplicationEvent(LoginFailedEvent event) {
		AuthenticationResponse source = (AuthenticationResponse) event.getSource();

		source.getMessage().ifPresent(s -> log.info("Login failed: {}", s));
		source.getAuthentication().ifPresent(a -> log.info("Login failed: {}", a));
	}

}
```

### Steps to Reproduce

1. wire in a LoginFailedEvent listener
2. provide wrong credentials to /login endpoint

### Expected Behaviour

In the event will be passed in the username which tried to login

### Actual Behaviour

There's nothing about the user

### Environment Information

- **Operating System**: Gentoo Linux edge
- **Micronaut Version:** 3.7.4
- **JDK Version:** 17.0.5

**Comment by francesco-monorchio** [comment]
Hi,

Authentication object is created after a successful login so, for this reason you don' t have it in that event. To resolve you can read the username from the HttpRequest using ServerRequestContext.currentRequest() method.
