### ISSUE TITLE
Passwords should be character arrays in UserState, PasswordEncoder and others

### ISSUE THREAD

**Issue by jachinte** [micronaut-projects/micronaut-security#119]
The [Java Cryptography Architecture Guide](https://docs.oracle.com/javase/6/docs/technotes/guides/security/crypto/CryptoSpec.html#PBEEx) and the [Secure Coding Guidelines for Java SE](https://www.oracle.com/technetwork/java/seccodeguide-139067.html#2) (Guideline 2-2) recommend that passwords should be stored in character arrays. In light of this, should methods [PasswordEncoder#encode(String)](https://github.com/micronaut-projects/micronaut-security/blob/master/security/src/main/java/io/micronaut/security/authentication/providers/PasswordEncoder.java#L31) and [UserState#getPassword():String](https://github.com/micronaut-projects/micronaut-security/blob/master/security/src/main/java/io/micronaut/security/authentication/providers/UserState.java#L36) be updated/deprecated in favor of `PasswordEncoder#encode(char[])` and `UserState#getPassword():char[]`?

Of course this change would include other classes that store passwords as strings, for example [these](https://github.com/micronaut-projects/micronaut-security/search?q=String+password&unscoped_q=String+password).

**Comment by alvarosanchez** [comment]
@jachinte good point. Are you willing to contribute the change?

**Comment by jachinte** [comment]
@alvarosanchez I can give it a try. I'm assuming that I should deprecate the methods using a String and add alternatives with the character array. May I ask you questions about this issue in case I need to?

**Comment by alvarosanchez** [comment]
@jachinte deprecate only is not an option. As per semantic versioning, incompatible API changes must me done in the next major version (2.x in this case).

There are workarounds, such as using default methods:

```java
default String encode(char[] rawPassword) {
    return encode(new String(rawPassword));
}
```

That would be backwards compatible and could be introduced in an upcoming 1.3.x release.

I haven't reviewed all places where passwords are managed. If you do, make sure there is an option to change them in a backwards compatible way.

**Comment by jachinte** [comment]
@alvarosanchez That's what I'm doing. I'm using existing tests to verify the changes are backwards-compatible.

**Comment by alvarosanchez** [comment]
Note that having the tests passing is not enough. Existing interfaces can't be changed in a minor release. That's why `default` alternatives need to co-exist until the old variants are removed in the next major version.

**Comment by hc-codersatlas** [comment]
Would also be good to wipe the `char[]` at the end of the request flow after all filters etc has been consumed.

**Comment by jameskleeh** [comment]
These APIs have been removed in 2.0, thus this is no longer an issue
