### ISSUE TITLE
Extensions object containing role key-value item is rendered when calling `/token_info` endpoint from native image service

### ISSUE THREAD

**Issue by montesmoci** [micronaut-projects/micronaut-security#1201]
### Expected Behavior

Under normal execution, the `/token_info` endpoint does not include the `extensions` object wrapper and, after jwt is parsed, is of the form

```json
{
"active":true,
 "username":"admin@example.com",
 "exp":1673462140,
 "iat":1673458540,
 "nbf":1673458540,
 "sub":"admin@example.com",
 "iss":"sampleapp",
 "permissionsLastUpdated":1673458296113,
 "roles":["ADMIN"],
 "name":"admin@example.com"
}
```

### Actual Behaviour

After Graal native image compilation and execution, the `/token_info` response is of the form:

```json
{
  "extensions": {
    "roles": [
      "ADMIN"
    ]
  },
  "active": true,
  "username": "admin@example.com",
  "exp": 1673910387,
  "iat": 1673906787,
  "nbf": 1673906787,
  "sub": "admin@example.com",
  "iss": "extensions-token-info"
}
```

### Steps To Reproduce

1. Build native image ./gradlew nativeCompile
2. Execute native image ./extensions-token-info
3. Authenticate with Basic Authentication at http://localhost:8080/login with credential Username = admin and Password = password
4. Request should respond with JWT cookie.
5. Perform GET http://localhost:8080/token_info request.
6. Observe the 'extensions' json object encompassing the roles array.

```json
{
  "extensions": {
    "roles": [
      "ADMIN"
    ]
  },
  "active": true,
  "username": "admin@example.com",
  "exp": 1673910387,
  "iat": 1673906787,
  "nbf": 1673906787,
  "sub": "admin@example.com",
  "iss": "extensions-token-info"
}
```

### Environment Information

- Version info: 'GraalVM 22.2.0 Java 17 CE'
- Java version info: '17.0.4+8-jvmci-22.2-b06'
- C compiler: cc (apple, arm64, 14.0.0)
- Garbage collector: Serial GC
- Micronaut: 3.8.1

### Example Application

https://github.com/montesmoci/extensions-token-info-native-image

### Version

3.8.1

**Comment by sdelamo** [comment]
can you try with [Micronaut Serialization](https://micronaut-projects.github.io/micronaut-serialization/latest/guide/) ?

**Comment by montesmoci** [comment]
I have created a branch that introduces Micronaut Serialization (``) and performed a GET request to `/token`. The following is the response I get from running the server and not compiling a native image.

```json
```

**Comment by sdelamo** [comment]
Close via https://github.com/micronaut-projects/micronaut-security/pull/1207
