### ISSUE TITLE
DefaultOAuthController does not redirect to failure endpoint on authentication error

### ISSUE THREAD

**Issue by maccuaa** [micronaut-projects/micronaut-security#1218]
### Expected Behavior

Redirect to "login-failure" URL after clicking cancel when performing OIDC login.

### Actual Behaviour

Callback returns AuthorizationErrorResponse JSON

### Steps To Reproduce

1. Configure an OIDC login provider
2. Initiate login to the SP
3. During login to the SP, cancel the authentication. Most SPs have a "cancel" or "go back" button
4. DefaultOpenIdClient [throws](https://github.com/micronaut-projects/micronaut-security/blob/master/security-oauth2/src/main/java/io/micronaut/security/oauth2/client/DefaultOpenIdClient.java#L138) an AuthorizationErrorResponseException which is not handled by [DefaultOauthController](https://github.com/micronaut-projects/micronaut-security/blob/master/security-oauth2/src/main/java/io/micronaut/security/oauth2/routes/DefaultOauthController.java#L91-L108)

Looking at the DefaultOauthClient, I believe the same issue would happen there as well.

Another discrepancy I noticed is the DefaultOauthClient wraps the exception in a `Flux.error` whereas the DefaultOpenIdClient does not.

### Environment Information

- Operating System: Ventura
- JDK Version: 17

### Version

3.9.0

### Similar Issue

- #605

**Comment by sdelamo** [comment]
@maccuaa `AuthorizationErrorResponseExceptionHandler` handling is done via [`AuthorizationErrorResponseExceptionHandler`](https://github.com/micronaut-projects/micronaut-security/blob/master/security-oauth2/src/main/java/io/micronaut/security/oauth2/endpoint/authorization/response/AuthorizationErrorResponseExceptionHandler.java)

**Comment by maccuaa** [comment]
Hi @sdelamo, i'm not sure what you're implying by that comment. Are you saying that an `AuthorizationErrorResponseException` should not redirect to the "login-failure" URL?

**Comment by sdelamo** [comment]
Latest version of Micronaut Security has a fix for this.
