### ISSUE TITLE
AuthenticationResponse throws 200 status code even if username and password are wrong

### ISSUE THREAD

**Issue by rgogulakrishnan** [micronaut-projects/micronaut-security#1222]
### Expected Behavior

Should throw 401 status. 

### Actual Behaviour

Sends 200 status code. Looks like AuthenticationExceptionHandler is not being invoked for failure or error cases. 

### Steps To Reproduce

1. Create an app with security-jwt and reactor features. 
2. Implement AuthUsernamePasswordProvider as mentioned in guide. 
3. Run app
4. Make a login request with wrong username and password. 

```
curl --request POST \
  --url http://localhost:8080/login \
  --header 'Content-Type: application/json' \
  --data '{
	"username": "sherlock",
	"password": "invalid"
}'
```

### Environment Information

Ubuntu and Windows
JDK17

### Example Application

https://github.com/rgogulakrishnan/mn-auth-issue

### Version

3.8.4

**Comment by rgogulakrishnan** [comment]
Updated example project.

**Comment by rgogulakrishnan** [comment]
Any update on this? Is this a bug?

**Comment by tuantrannav** [comment]
according to the javadoc:

A 303 HTTP Response or 200 HTTP Response if loginFailure is null, for example if RedirectConfiguration is disabled.

It seems if you dont enable redirect it will respond 200 OK. I wonder if it should return 401 instead.

**Comment by sdelamo** [comment]
When you set `micronaut.security.authentication` to  `cookie` you enable `JwtCookieLoginHandler` which extends from `CookieLoginHandler`. 

The failure case when you don't want a redirect current returns a 200 intentionally. We have tests for that. @rgogulakrishnan a nd @tuantrannav  I agree with you that maybe a 401 maybe more idiomatic for the non redirect scenario. This may consider a breaking change. Thus, I am going to send the change to master which is the branch which targets Micronaut Framework 4. 

In the meanwhile if you want you can change the behaviour by providing a replacement

Add such a class to your project:

```java
package com.example;

import io.micronaut.context.annotation.Replaces;
import io.micronaut.core.annotation.Nullable;
import io.micronaut.http.HttpRequest;
import io.micronaut.http.HttpResponse;
import io.micronaut.http.MutableHttpResponse;
import io.micronaut.security.authentication.AuthenticationResponse;
import io.micronaut.security.config.RedirectConfiguration;
import io.micronaut.security.config.RedirectService;
import io.micronaut.security.errors.PriorToLoginPersistence;
import io.micronaut.security.token.jwt.cookie.AccessTokenCookieConfiguration;
import io.micronaut.security.token.jwt.cookie.JwtCookieLoginHandler;
import io.micronaut.security.token.jwt.cookie.RefreshTokenCookieConfiguration;
import io.micronaut.security.token.jwt.generator.AccessRefreshTokenGenerator;
import io.micronaut.security.token.jwt.generator.AccessTokenConfiguration;
import jakarta.inject.Singleton;

import java.net.URI;
import java.net.URISyntaxException;

@Replaces(JwtCookieLoginHandler.class)
@Singleton
public class TokenCookieLoginHandlerReplacement extends JwtCookieLoginHandler {

    public TokenCookieLoginHandlerReplacement(RedirectService redirectService, RedirectConfiguration redirectConfiguration, AccessTokenCookieConfiguration accessTokenCookieConfiguration, RefreshTokenCookieConfiguration refreshTokenCookieConfiguration, AccessTokenConfiguration accessTokenConfiguration, AccessRefreshTokenGenerator accessRefreshTokenGenerator, @Nullable PriorToLoginPersistence priorToLoginPersistence) {
        super(redirectService, redirectConfiguration, accessTokenCookieConfiguration, refreshTokenCookieConfiguration, accessTokenConfiguration, accessRefreshTokenGenerator, priorToLoginPersistence);
    }


    @Override
    public MutableHttpResponse<?> loginFailed(AuthenticationResponse authenticationFailed, HttpRequest<?> request) {
        try {
            if (loginFailure == null) {
                return HttpResponse.unauthorized();
            }
            URI location = new URI(loginFailure);
            return HttpResponse.seeOther(location);
        } catch (URISyntaxException e) {
            return HttpResponse.serverError();
        }
    }
}
```
