### ISSUE TITLE
How can I retrieved the HttpRequest body upon AuthorizationException

### ISSUE THREAD

**Issue by osi-mbermundo** [micronaut-projects/micronaut-security#1223]
### Issue description

- Objective: Get the HttpRequest body for auditting, this is to log the request payload if this a faulty request or an attack
- Issue: On exception handler for AuthorizationException, the HttpRequest.getBody() returns an Optional.empty

I also log on AuthenticationProvider (security) and HttpServerFilter (filter) level, only the HttpRequest attributes are available, and HttpRequest.getBody() returns an Optional.empty

Is this an expected behavior or I might misconfigured the authentication and filter?

**Comment by sdelamo** [comment]
It is expected behaviour that Body of the request is not available in filters.

**Comment by osi-mbermundo** [comment]
> It is expected behaviour that Body of the request is not available in filters.

Thanks for confirming
