### ISSUE TITLE
Implicit security is 403 for everything by default

### ISSUE THREAD

**Issue by haris-zynka** [micronaut-projects/micronaut-security#123]
Micronaut: 1.2.7
Micronaut security: 1.2.2

So I was trying to login using JWT and continue on with using the API but everything returned 403.
I understand that by default all of the route refuse everything if not explicitly specified what kind of users could go in. I'm not sure is this a good practice but I would suggest at least to have application.yaml option to put in something like default-level: isAuthenticated. Now I have to explicitly map all the routes (annotation or yaml for interception) to enable them to be used by logged in users.

**Comment by alvarosanchez** [comment]
This is by design. The assumption behind it is that, if everything were open by default, if you forget to guard a new URL, it can take a long time to discover that users had access, whereas if you forget to open access for allowed users when using the locked-down-by-default approach, nobody can access the URL and the error will be quickly discovered. This approach is more work, but much safer.

It is already possible to have an application open by default. Read [the documentation](https://micronaut-projects.github.io/micronaut-security/latest/guide/#interceptUrlMap) about how to do it.

**Comment by haris-zynka** [comment]
> This is by design. The assumption behind it is that, if everything were open by default, if you forget to guard a new URL, it can take a long time to discover that users had access, whereas if you forget to open access for allowed users when using the locked-down-by-default approach, nobody can access the URL and the error will be quickly discovered. This approach is more work, but much safer.
> 
> It is already possible to have an application open by default. Read [the documentation](https://micronaut-projects.github.io/micronaut-security/latest/guide/#interceptUrlMap) about how to do it.

I do not understand the "It is already possible to have an application open by default. Read the documentation about how to do it." as this only explains the part on how to configure security which I did.

As I specified I had to do either application.yml or map configuration, which I did by choosing to add:
`pattern: /**
        access:
          - isAuthenticated()`
in application.yml.

The reason I asked (and assumed that it's intentional) is that the documentation does not specify anywhere **1 single parameter** that will allow logged in users to access everything except for routes that specify additional checks like annotations for role checking above methods or this intercept-url part.

I actually asked for something like:
`micronaut.security.default-access: isAuthenticated()`

But anyways thanks it's quite understandable to keep it this way.

**Comment by alvarosanchez** [comment]
> The reason I asked (and assumed that it's intentional) is that the documentation does not specify anywhere **1 single parameter** that will allow logged in users to access everything except for routes that specify additional checks like annotations for role checking above methods or this intercept-url part.

Sorry, I might not be understanding your question. `pattern: /** access: - isAuthenticated()` combined with those additional route rules will give you what you want.

**Comment by haris-zynka** [comment]
> > The reason I asked (and assumed that it's intentional) is that the documentation does not specify anywhere **1 single parameter** that will allow logged in users to access everything except for routes that specify additional checks like annotations for role checking above methods or this intercept-url part.
> 
> Sorry, I might not be understanding your question. `pattern: /** access: - isAuthenticated()` combined with those additional route rules will give you what you want.

No problem, I just asked should it be considered to have 1 parameter like `micronaut.security.default-access: isAuthenticated()` without extra pattern field. Reason is that sometimes I have to think about order of the items in intercept part like:

`intercept-url-map:
      -
        pattern: /swagger-ui/**
        access:
          - isAnonymous()
        pattern: /**
        access:
          - isAuthenticated()`

If you put it in different order it makes swagger-ui only for authenticated users. This is just an example. But it's doable with intercept-uri-map so just a question of should it be considered at all for easier manipulation to put default access somewhere else.

**Comment by alvarosanchez** [comment]
You can raise a feature request about that config option, and if it gets traction, we can consider it.

You can also have a try yourself and send a PR. Contributions are always welcomed.
