### ISSUE TITLE
Refresh cookie path problem.

### ISSUE THREAD

**Issue by millmanw** [micronaut-projects/micronaut-security#1271]
### Expected Behavior

When an application is using cookie authentication and has the context-path defined the /oauth/access_token path on the refresh cookie should include the context-path.

Resulting in a refresh cookie with a path of
/**_{context-path}_**/oauth/access_token

### Actual Behaviour

The generation of the refresh token does not include the context-path when it is set so the refresh cookie is unusable.

Regardless of the context-path the path on a refresh cookie is always /oauth/access_token

Setting the _micronaut.security.endpoints.oauth.path_ to include the context path writes the correct path into the refresh cookie but it also move the REST resource.  So its not a viable solution either.

### Steps To Reproduce

1. Create a sample cookie authentication app with the refresh cookie enabled and a context-path defined.
2. Example application config
`micronaut:
  server:
     context-path: /auth
  security:
    authentication: cookie
    redirect:
      enabled: true
      login-success: /auth/userInfo
      refresh:
        url: /auth/userInfo
        token:
      jwt:
        cookie:
          enabled: true
          cookie-same-site: strict
          cookie-path: /
        signatures:
          secret:
            generator:
              secret: '"${JWT_GENERATOR_SIGNATURE_SECRET:pleaseChangeThis}"'
        generator:
          refresh-token:
            secret: '"${JWT_GENERATOR_SIGNATURE_SECRET:pleaseChangeThis}"'
            enabled: true`
3. Login and attempt to refresh
    1. The refresh token will be generated with path /oauth/access_token. which is invalid to use when calling the actual refresh path /auth/oauth/access_token

### Environment Information

- Ubuntu & Mac
- Java version 17.0.5

### Version

3.7.3

**Comment by sdelamo** [comment]
thanks for reporting @millmanw I will check this soon

**Comment by sdelamo** [comment]
@millmanw https://github.com/micronaut-projects/micronaut-security/pull/1276 should solve your issue. 

As a workaround while we release a new version, you could replace `JwtCookieLoginHandler` to fix the path.
