### ISSUE TITLE
Resource access based roles with @Secured annotation

### ISSUE THREAD

**Issue by TeNNoX** [micronaut-projects/micronaut-security#13]
Hello, I'm trying to get a micronaut microservice working with OpenID Connect.
I managed to get the basic setup working eventually (with help of **micronaut-oauth2**).

But when trying to set up role-based authentication via `@Secured`, I noticed that the default [`SecuredAnnotationRule`](https://github.com/micronaut-projects/micronaut-core/blob/master/security/src/main/java/io/micronaut/security/rules/SecuredAnnotationRule.java) cannot parse roles from the JWT generated by Keycloak. It is able to get list of roles from an Iterable, but the format is:
```json
{
  "realm_access": {
    "roles": [
      "global_role_1"
    ]
  },
  "resource_access": {
    "resource_1": {
      "roles": [
        "resource_specific_role_1"
      ]
    }
  }
}
```

Unfortunately, I cannot (simply) extend the `SecuredAnnotationRule` nor the the `AbstractSecurityRule` as their constructors are package-private.

Do you plan to support resource-based authorization?

Should I create an issue for this in *micronaut-core*?

**Comment by pmcneil** [comment]
I know this is a little down the track, but... It's a little obscure but you can change the way the roles are mapped in Keycloak to produce a simple roles: ["role1", role2"] mapping.
You can find it in the keycloak UI via `Client Scopes -> roles -> Mappers -> client roles` and change the `token claim name` from something like `resource_access.${client_id}.roles` to just `roles`

hope that helps someone :-)
