### ISSUE TITLE
How do we load this project into Intellij Idea

### ISSUE THREAD

**Issue by thomasq0** [micronaut-projects/micronaut-security#1319]
### Issue description

I was trying to clone and load this git project into my Intellij Idea. But the gradle build failed to be refreshed.
In master, I got a bunch of errors like this:
> Build file '/Users/thomas.qiu/projects/mnf/micronaut-security/build.gradle' line: 2
> 
> An exception occurred applying plugin request [id: 'io.micronaut.build.internal.docs']
> \> Failed to apply plugin class 'io.micronaut.build.docs.JavadocAggregatorPlugin'...

And then I switched to branch 4.0.x, the error became:
> Could not resolve all files for configuration 'classpath'.
> \> Could not find null:groovydoc-gradle-plugin:null.

Do you have guide about how to do that? Alternatively, is there a more convenient way to navigate around to see how it works. For example, I'd like to know how `TokenValidator` is used to authenticate a request.

**Comment by sdelamo** [comment]
You should be able to import into intellij after https://github.com/micronaut-projects/micronaut-security/pull/1312
