### ISSUE TITLE
RSASignatureGeneratorConfiguration documentation unclear

### ISSUE THREAD

**Issue by JoergAdler** [micronaut-projects/micronaut-security#140]
Hi,

I just tried to bring a RSASignatureGeneratorConfiguration up like it is stated in https://micronaut-projects.github.io/micronaut-security/latest/guide/#jwtGeneratorSignature. Unfortunately, the named "generator" bean is not the RSASignatureGeneratorConfiguration but the SignatureGeneratorConfiguration class. 

So to bring it up, I had to insert the following factory. I don't know if it is intended behavior?

```java
@Factory
public class MySignatureGeneratorConfigurationFactory {
    @Bean
    @Named("generator")
    public SignatureGeneratorConfiguration signatureGeneratorConfiguration(RSASignatureGeneratorConfiguration configuration) {
        return new RSASignatureGenerator(configuration);
}
```

Would be great if you would  consider to update the documentation :-)

**Comment by alvarosanchez** [comment]
The documentation does say that the bean needs to be qualified with the name `generator`, which is exactly what you did.

What is what you think is missing in the documentation?

**Comment by JoergAdler** [comment]
The doc states "you need to have in your app a bean of type RSASignatureGeneratorConfiguration, ECSignatureGeneratorConfiguration, SecretSignatureConfiguration qualified with name generator" which is unclear, as it looks like that you can choose between the three.

In fact, it is "you need to have in your app a bean of type SecretSignatureConfiguration qualified with name generator". So erasing the two other class names will help. Maybe also add the example?

Another possibility will be to state 
"you need to have in your app a bean of type RSASignatureGenerator, ECSignatureGenerator, SecretSignatureConfiguration qualified with name generator" 
As RSASignatureGenerator inherits from SecretSignatureConfiguration?

**Comment by alvarosanchez** [comment]
Would you be willing to contribute the first option, including your example?

**Comment by JoergAdler** [comment]
Of course. Pull request is there :-)
