### ISSUE TITLE
Override validateToken() from JwtTokenValidator

### ISSUE THREAD

**Issue by haaah** [micronaut-projects/micronaut-security#1426]
### Expected Behavior

The IDE should be able to override the function validateToken().

Previously when using Micronaut 3X i was able to override the validateToken() by 
`@Override
Publisher<Authentication> validateToken(String token, HttpRequest<?> request) {}`

But on the recent updated Micronaut 4X the code from JwtTokenValidator.java has been updated to 

`
    public Publisher<Authentication> validateToken(String token, @Nullable T request) {
        return validator.validate(token, request)
                .flatMap(jwtAuthenticationFactory::createAuthentication)
                .map(Flux::just)
                .orElse(Flux.empty());
    }
`

### Actual Behaviour

`
Method 'validateToken' from class 'security.FireBaseTokenValidator' does not override method from its superclass or interfaces but is annotated with @Override.
 @ line 32, column 3.
     @Override
     ^
`

### Environment Information

- Micronaut 4.0.5
- Micronaut Security 4.0.4
- Micronaut Security JWT 4.0.4

### Version

4.0.5

**Comment by sdelamo** [comment]
You will have to update for `FireBaseTokenValidator` class.
