### ISSUE TITLE
Secured Failed to compile evaluated expression [[#{ user?.attributes?.get('email') == 'sherlock@micronaut.example' }]]

### ISSUE THREAD

**Issue by dajay** [micronaut-projects/micronaut-security#1490]
### Expected Behavior

Can access to endpoint if authenticated user is sherlock@micronaut.example'

### Actual Behaviour

java: Failed to compile evaluated expression [[#{ user?.attributes?.get('email') == 'sherlock@micronaut.example' }]]. Cause: No element with name [user] available in evaluation context

### Steps To Reproduce

copy paste exemple https://micronaut-projects.github.io/micronaut-security/latest/guide/index.html#securedExpression

### Environment Information

jdk 17

### Example Application

https://micronaut-projects.github.io/micronaut-security/latest/guide/index.html#securedExpression

### Version

4.1.0

**Comment by graemerocher** [comment]
is `micronaut-security-annotations` on your annotation processor classpath?

**Comment by dajay** [comment]
Issue is the same with or without micronaut-security-annotations

**Comment by timyates** [comment]
I created a micronaut 4.1.0 application with

```
mn create-app --features=security test
```

I added a class `ExampleController` and copied the source from the linked documentation

And `./gradlew build` worked as expected

I also tried with a maven application via:

```
mn create-app --features=security --build=maven test
```

This also worked when I ran `./mvnw test`

I'm going to close this for now as I cannot reproduce it

@dajay If you have a simple reproducer that shows the issue you're seeing, please add it here and we can take another look 👍
