### ISSUE TITLE
Micronaut 4 upgrade document does not mention about the breaking changes of Micronaut Security

### ISSUE THREAD

**Issue by vikas-shrivastav-mns** [micronaut-projects/micronaut-security#1549]
### Expected Behavior

Micronaut 4 upgrade document does not mention about the breaking changes of Micronaut Security  where the configuration changes has been modified

https://micronaut.io/2023/05/09/upgrade-to-micronaut-framework-4-0-0/

Link for Micronaut Security 
https://micronaut-projects.github.io/micronaut-security/latest/guide/#breaks

It will be really helpful if this is updated in  upgrade document.

### Version

4.2.1

**Comment by sdelamo** [comment]
@vikas-shrivastav-mns do you think we should link from the blog post to every module breaking changes documentation?

**Comment by sdelamo** [comment]
I added the following to the blog post: 

> Read the [Breaking Changes](https://micronaut-projects.github.io/micronaut-security/latest/guide/#breaks) and [What's New](https://micronaut-projects.github.io/micronaut-security/latest/guide/#whatsNew) sections of the Micronaut Security documentation.
