### ISSUE TITLE
security-processor module

### ISSUE THREAD

**Issue by sdelamo** [micronaut-projects/micronaut-security#1588]
Create a `security-processor` module. 
Move annotation mappers in `security-annotations` into this new module. 

Update documentation instead of doing: 

```kotlin
annotationProcessor("io.micronaut.security:micronaut-security-annotations")
implementation("io.micronaut.security:micronaut-security") 
```

They will do: 
```kotlin
annotationProcessor("io.micronaut.security:micronaut-security-processor")
implementation("io.micronaut.security:micronaut-security") 
```

`micronaut-security-annotations` is api dependency of `micronaut-security`.

**Comment by graemerocher** [comment]
why?
