### ISSUE TITLE
OAuth2 flow Authorization Token is duplicated when Retry occurs with Rxjava

### ISSUE THREAD

**Issue by vimaldermal** [micronaut-projects/micronaut-security#1619]
### Expected Behavior

Header Authorization should be present in request only once

### Actual Behaviour

Header Authorization  is added up in each retry

### Steps To Reproduce

Add the below configurations in application.yml
 security:
    enabled: true
    oauth2:
      clients:
       server-service:
          client-id: 123
          client-secret: 345
          grant-type: client_credentials
          token:
            url: http://localhost:8083/token
            auth-method: client_secret_post
          client-credentials:
            service-id-regex: ".*"

Create a client
			
@Client(id = "360-service", path = "/test")
@Retryable(delay = "10ms", attempts = "2", maxDelay = "2s")
       
public interface MyServiceClient {

    @Post("/users/search")
    Single<MyResponse> getUserId(@Body MyRequest myRequest);
}

when the client is invoked and retry happens due to some reason(BadRequest ex), Authorization token is added up  two times in the next request and 3 times in the next retry request

### Environment Information

JDK 17

### Example Application
https://github.com/vimaldermal/micronaut3.git

_No response_

### Version

3.10.1

**Comment by sdelamo** [comment]
do you have a sample app? does it happen in Micronaut Framework 4?

**Comment by vimaldermal** [comment]
@sdelamo.Need to check if this is in micronaut 4.

**Comment by vimaldermal** [comment]
hi @sdelamo is this a  bug in the micronaut ? We tried http filters  even with order, still facing same issue

**Comment by sdelamo** [comment]
I don't know how to reproduce the issue you are describing.

**Comment by vimaldermal** [comment]
@sdelamo  Attaching a sample multi module project 

execute GET localhost:8081/client-user/BasherTest and can see token is duplicate on the client call


[micronaut-sample-main.zip](https://github.com/micronaut-projects/micronaut-security/files/14583711/micronaut-sample-main.zip)

**Comment by vimaldermal** [comment]
@sdelamo  I have added a sample application.

It has 3 modules
clientApp (running  in 8081)
serverApp (running  in 8082)
tokenApp (running  in 8083)

Execute the client app GET localhost:8081/client-user/BasherTest.
This will first call the token endpoint and fetch the token and call the serverApp.
From serverApp, 400 will be received and clientApp will retry the request which will add  the Authorization token again.
micronaut client log is enabled at TRACE level in clientApp, so you should be able to see the token getting addedUp.

**Comment by jeremyg484** [comment]
The source of the issue is a bug in the way `@Retryable` works with the declarative HTTP client with any type of reactive return value. This is fixed by https://github.com/micronaut-projects/micronaut-core/pull/10626

**Comment by vimaldermal** [comment]
@jeremyg484  @sdelamo is the next release expected is 4.3.7 or 4.4.0 ?

**Comment by jeremyg484** [comment]
@vimaldermal I believe there will be a 4.3.7 release, but this particular change that had to be made to `HttpClientIntroductionAdvice` is big enough that we thought it better to move it to 4.4.0, which is currently targeting an April 4th release.

**Comment by vimaldermal** [comment]
@jeremyg484  Thanks for the update.
