### ISSUE TITLE
Docs: Token Propagation requires io.micrometer:context-propagation

### ISSUE THREAD

**Issue by ArnauAregall** [micronaut-projects/micronaut-security#1629]
### Issue description

Reading the reference docs there is no specific mention that Token Propagation feature requires dependency `io.micrometer:context-propagation` dependency [to work properly](https://github.com/micronaut-projects/micronaut-security/blob/master/security/src/main/java/io/micronaut/security/token/propagation/TokenPropagationHttpClientFilter.java#L68) (spent some time debugging it).

Also on the samples of the guides, the dependency is not mentioned explicitly but added on all submodules (`gateway`, `userecho`, `intermediate-gateway`, `intermediate-user`).

Opening the issue to reference it in a a PR I'll open in order to add a specific mention for the needed dependency. 🙂

**Comment by sdelamo** [comment]
Thanks for reporting @ArnauAregall we would need add a link to the  [Reactor Context Propagation](https://docs.micronaut.io/latest/guide/#reactorContextPropagation) documentation from the token propagation section.
