### ISSUE TITLE
JWT refresh token has same role grants as access token

### ISSUE THREAD

**Issue by julKali** [micronaut-projects/micronaut-security#163]
When using the built-in JWT features, the refresh token has exactly the same role grants as the access token. In fact, it is an exact copy of the access token only the expiration date is not present. 

Example:
When using the login controller with a valid set of credentials, you receive something like this:
```
{
    "username": "example",
    "roles": [
        "GENERAL"
    ],
    "access_token": "eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJleGFtcGxlIiwibmJmIjoxNTgwMTE5NDI1LCJyb2xlcyI6WyJHRU5FUkFMIl0sImlzcyI6Im1udXNlcmF1dGgiLCJleHAiOjE1ODAxMjMwMjUsImlhdCI6MTU4MDExOTQyNX0.LvTBmpK9FRCt5pUu_cMuRvVlTXGHkywQJncTH8wtYJs",
    "refresh_token": "eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJleGFtcGxlIiwibmJmIjoxNTgwMTE5NDI1LCJyb2xlcyI6WyJHRU5FUkFMIl0sImlzcyI6Im1udXNlcmF1dGgiLCJpYXQiOjE1ODAxMTk0MjV9.OuQ5O1dM08p2TEpMiea8iAKLLrtCvUA8pY0rf6CJ-Z8",
    "token_type": "Bearer",
    "expires_in": 3600
}
```
If you decode the access token, you will get the following payload:
```
{
  "sub": "example",
  "nbf": 1580119425,
  "roles": [
    "GENERAL"
  ],
  "iss": "mnuserauth",
  "exp": 1580123025,
  "iat": 1580119425
}
```
For the refresh token, it looks like this:
```
{
  "sub": "example",
  "nbf": 1580119425,
  "roles": [
    "GENERAL"
  ],
  "iss": "mnuserauth",
  "iat": 1580119425
}
```
As you can see, the only thing that's different is the expiration time which is missing in the refresh token. In my view, this defies the purpose of a refresh token. Basically, one could use the refresh token forever (as it has the same grants as the actualy access token) instead of properly using the access token and refreshing it every now and then.

**Comment by jameskleeh** [comment]
Going to close this in favor of the other issue that was created that brings up the larger issue https://github.com/micronaut-projects/micronaut-security/issues/174
