### ISSUE TITLE
X509 Certificate Authentication

### ISSUE THREAD

**Issue by kastork** [micronaut-projects/micronaut-security#165]
Feature request

It would be great if Micronaut had this out of the box with clear instructions on setting up the necessary certificate stores server-side.  Especially the procedure for creating the certificate stores and configuration for complicated PKI like the US DoD's CAC cards, which have 5 root CA's and dozens of intermediate ones.

**Comment by jameskleeh** [comment]
@kastork This would be a matter of implementing an AuthenticationFetcher and returning the UserDetails created from the data in the certificate. I'm not sure what implementation we could create that would be a sensible default. Is the data in the certificate standard across all applications that use this type of authentication?

**Comment by kastork** [comment]
@jameskleeh 

My detailed case was an effort to answer your question.  You are right that some aspects of using the certificate info will necessarily be application-specific (or at least specific to the particular certificate setup of a given organization).  But (at least when I filed this issue) there was no (documented) way to  do the first part of the use case via Micronaut server configuration.

That is, there is (was?) no way to just set some properties and have the server demand a client certificate *for certain endpoints* and then have a documented approach for accessing certificate data writing the application code that does its own thing with the certificate data to allow or deny access to that route -- i.e. in a way that integrates with the existing security framework.

Perhaps things have changed, my projects over the last few months haven't been server-side, so I haven't stayed up to date with Micronaut progress.

Thanks to you and the team for remaining engaged with this.

**Comment by jameskleeh** [comment]
@kastork Thanks for the reply. It seems its possible to do this via the method I described above. One aspect that isn't supported is the "for certain endpoints" portion. We don't currently support only allowing a subset of the authentication fetchers based on the endpoint. Each fetcher is attempted for each request. I'll leave this issue open to act as a request for an example project or documentation on how to achieve this.

**Comment by kastork** [comment]
@jameskleeh  Thanks, that will be a great start.

**Comment by kastork** [comment]
@jameskleeh 

James,  I've found a great write up of the functionality that I'm looking for in the KeyCloak documentation. It may help.

https://github.com/keycloak/keycloak-documentation/blob/master/server_admin/topics/authentication/x509.adoc

**Comment by jameskleeh** [comment]
@kastork Can you try this on your end and let me know the results. I don't know what is required to get X509 going locally. Create an AuthenticationFetcher implementation that calls `request.getCertificate()`. If the certificate is present, extract the details and create an `Authentication` object. If it meets your needs, we can put together an example/guide from there.

**Comment by moazharuddin** [comment]
@jameskleeh request.getCertificate() is returning empty.
https://stackoverflow.com/questions/63353788/not-able-to-fetch-client-certificate-in-authenticationfetcher-micronaut
