### ISSUE TITLE
Google oauth2 Micronaout 1.3

### ISSUE THREAD

**Issue by menesty** [micronaut-projects/micronaut-security#172]
Micronout 1.3
Java : 11
Get exception
```
throw google account get Exception
08:13:40.741 [nioEventLoopGroup-3-37] ERROR i.m.s.t.j.s.jwks.DefaultJwkValidator - JOSEException when verifying jwt
com.nimbusds.jose.JOSEException: Unsupported JWS algorithm HS256, must be RS256, RS384, RS512, PS256, PS384 or PS512
at com.nimbusds.jose.crypto.impl.RSASSA.getSignerAndVerifier(RSASSA.java:81)
at com.nimbusds.jose.crypto.RSASSAVerifier.verify(RSASSAVerifier.java:159)
at com.nimbusds.jose.JWSObject.verify(JWSObject.java:356)
at io.micronaut.security.token.jwt.signature.jwks.DefaultJwkValidator.validate(DefaultJwkValidator.java:49)
at io.micronaut.security.token.jwt.signature.jwks.JwksSignature.lambda$verify$2(JwksSignature.java:209)
```
configuration

```yaml
  security:
    enabled: true
    endpoints:
      login:
        enabled: true
      logout:
        enabled: true
       get-allowed: true
      oauth:
        enabled: true
    session:
      enabled: true
    token:
      jwt:
        enabled: true
        cookie:
          enabled: true
          loginFailureTargetUrl: /login/authFailed
        signatures:
          secret:
            generator:
              secret: **
    oauth2:
      enabled: true
      clients:
        google:
          client-id: '**'
          client-secret: '**'
          openid:
            issuer: 'https://accounts.google.com'
```

**Comment by abedurftig** [comment]
I have the very same issue (happens also in Micronaut 1.3.1). I just downgraded again to Micronaut 1.2.9 and there the issue does not exist.

**Comment by morki** [comment]
1.3.0 is also working, version 1.3.1 not

**Comment by jameskleeh** [comment]
@morki @abedurftig @menesty Can one of you upload a sample application? I can't reproduce

**Comment by jameskleeh** [comment]
https://www.googleapis.com/oauth2/v3/certs Only returns the RS256 algorithm so I don't know where HS256 is coming from.

**Comment by jameskleeh** [comment]
https://accounts.google.com/.well-known/openid-configuration even only contains ``` "id_token_signing_alg_values_supported": [
  "RS256"
 ],```

**Comment by morki** [comment]
@jameskleeh I think it is not related to google at all, but to algorithm of **micronaut's** jwt token generation and validation. 

Project: https://github.com/morki/micronaut-jwt-test

Steps:
- run ./gradlew run
- go to http://localhost:8080/oauth/login/google
- after return, you see "Not authenticated"
- in console, there is error

**Comment by menesty** [comment]
@morki I am agree with you, it look like depend to jwt - but I get this exception only when connect oauth google, I create simple test project - auth with google work but still get 
 ERROR io.micronaut.security.token.jwt.signature.jwks.DefaultJwkValidator - JOSEException when verifying jwt
com.nimbusds.jose.JOSEException: Unsupported JWS algorithm HS256, must be RS256, RS384, RS512, PS256, PS384 or PS512
	at com.nimbusds.jose.crypto.impl.RSASSA.getSignerAndVerifier(RSASSA.java:81)
	at com.nimbusds.jose.crypto.RSASSAVerifier.verify(RSASSAVerifier.java:159)
	at com.nimbusds.jose.JWSObject.verify(JWSObject.java:356)
	at io.micronaut.security.token.jwt.signature.jwks.DefaultJwkValidator.validate(DefaultJwkValidator.java:49)
	at io.micronaut.security.token.jwt.signature.jwks.JwksSignature.lambda$verify$2(JwksSignature.java:209)
