### ISSUE TITLE
Missing GraalVM configuration

### ISSUE THREAD

**Issue by morki** [micronaut-projects/micronaut-security#176]
There is some missing configuration for oauth2/oidc security. See https://github.com/micronaut-guides/micronaut-oauth2-okta/issues/6

Error:

```
Caused by: io.micronaut.http.codec.CodecException: Error decoding JSON stream for type [class io.micronaut.security.oauth2.client.DefaultOpenIdProviderMetadata]: Class com.fasterxml.jackson.databind.PropertyNamingStrategy$SnakeCaseStrategy has no default (no arg) constructor
```

This can be solved by adding `com.fasterxml.jackson.databind.PropertyNamingStrategy$SnakeCaseStrategy` to `@TypeHint` annotation like this:

```java
@TypeHint(typeNames = {
    "com.fasterxml.jackson.databind.PropertyNamingStrategy$SnakeCaseStrategy"
})
```

I think it has to be in this project, because it relates to it, not tu application configuration.
But then it fails in runtime with another error that I cannot figure out how to solve:

```
Failed to serialize the authorization request state to JSON
com.fasterxml.jackson.databind.exc.InvalidDefinitionException: No serializer found for class io.micronaut.security.oauth2.endpoint.authorization.state.DefaultState and no properties discovered to create BeanSerializer (to avoid exception, disable SerializationFeature.FAIL_ON_EMPTY_BEANS)
```

Can you please point me to the right way? I would be happy to create PR then.

**Comment by alvarosanchez** [comment]
I think where it should really be included is here: https://github.com/micronaut-projects/micronaut-core/blob/master/runtime/src/main/java/io/micronaut/jackson/JacksonConfiguration.java#L42

**Comment by morki** [comment]
@alvarosanchez ok agree, what about a second exception? I tried add  `io.micronaut.security.oauth2.endpoint.authorization.state.DefaultState` to `@TypeHint` with `ALL_DECLARED_FIELDS` but it did not help.

**Comment by morki** [comment]
@alvarosanchez maybe annotating class [DefaultState](https://github.com/micronaut-projects/micronaut-security/blob/master/security-oauth2/src/main/java/io/micronaut/security/oauth2/endpoint/authorization/state/DefaultState.java) with `@Introspected` can help?

**Comment by morki** [comment]
The proposed solution seems to work. I will made PR...
