### ISSUE TITLE
Violation of OpenID Connect discovery spec breaks OIDC login flow

### ISSUE THREAD

**Issue by meredrica** [micronaut-projects/micronaut-security#1774]
### Expected Behavior

OIDC connect flow should follow the official specs and not crash with additional `token_endpoint_auth_methods_supported` types.

### Actual Behaviour

When starting an OIDC flow with a provider that sends values that are not listed in the [AuthenticationMethod](https://github.com/micronaut-projects/micronaut-security/blob/4.10.x/security-oauth2/src/main/java/io/micronaut/security/oauth2/endpoint/AuthenticationMethod.java) enum, the value cannot be parsed to an enum constant and thus crashes.

The OpenID Connect Discovery Spec explicitly allows sending arbitrary additional methods in `token_enpoint_auth_methods_supported`, see here: https://openid.net/specs/openid-connect-discovery-1_0.html#ProviderMetadata (...  Other authentication methods **MAY be defined by extensions**...)

Spring faced the same problem, here is the related issue: https://github.com/spring-projects/spring-security/issues/4313

The issue stems from the code in `OpenIdProviderMetadata` that parses the authentication method here: [OpenIdProviderMetadata#getTokenEndpointAuthMethods](https://github.com/micronaut-projects/micronaut-security/blob/4.10.x/security-oauth2/src/main/java/io/micronaut/security/oauth2/client/OpenIdProviderMetadata.java#L375)

It uses the `AuthenticationMethod` class, which links to the [OpenId Connect Core>Client Authentication](https://openid.net/specs/openid-connect-core-1_0.html#ClientAuthentication) and to [Mutual TLS Profiles for OAuth Clients](https://datatracker.ietf.org/doc/html/draft-campbell-oauth-mtls) and, as far as I can tell, implements the union of all authentications mentioned there. Note that the [Mutual TLS auth for Oauth 2.0](https://datatracker.ietf.org/doc/html/rfc8705#section-2.2.1) RFC also contains the (in this case) offending `self_signed_tls_client_auth` method.

All the different (and somewhat confusing) RFCs and specs aside, it's valid to specify arbitrary values in `token_endpoint_auth_methods_supported` under the OpenID connect discovery spec, but this is currently not supported.

A full stack is attached, I think the interesting parts are these:
```
ERROR i.m.http.server.RouteExecutor - Unexpected error occurred: No enum constant io.micronaut.security.oauth2.endpoint.AuthenticationMethod.SELF_SIGNED_TLS_CLIENT_AUTH
java.lang.IllegalArgumentException: No enum constant io.micronaut.security.oauth2.endpoint.AuthenticationMethod.SELF_SIGNED_TLS_CLIENT_AUTH
at java.base/java.lang.Enum.valueOf(Unknown Source)
at io.micronaut.security.oauth2.endpoint.AuthenticationMethod.valueOf(AuthenticationMethod.java:26)
at java.base/java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
at java.base/java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source)
at java.base/java.util.stream.AbstractPipeline.copyInto(Unknown Source)
at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(Unknown Source)
at java.base/java.util.stream.AbstractPipeline.evaluate(Unknown Source)
at java.base/java.util.stream.ReferencePipeline.collect(Unknown Source)
at io.micronaut.security.oauth2.client.OpenIdProviderMetadata.getTokenEndpointAuthMethods(OpenIdProviderMetadata.java:378)
at io.micronaut.security.oauth2.client.DefaultOpenIdClient.getTokenEndpoint(DefaultOpenIdClient.java:169)
at io.micronaut.core.util.SupplierUtil$1.get(SupplierUtil.java:47)
at io.micronaut.security.oauth2.client.DefaultOpenIdClient.onCallback(DefaultOpenIdClient.java:153)
at io.micronaut.security.oauth2.routes.DefaultOauthController.callback(DefaultOauthController.java:143)
at io.micronaut.security.oauth2.routes.$DefaultOauthController$Definition$Exec.dispatch(Unknown Source)
at io.micronaut.context.AbstractExecutableMethodsDefinition$DispatchedExecutableMethod.invoke(AbstractExecutableMethodsDefinition.java:456)

```
[stack.txt](https://github.com/user-attachments/files/16710719/stack.txt)

### Steps To Reproduce

Configure an OpenID provider to return other `token_endpoint_auth_methods_supported` that are not in the Enum, here this is `self_signed_tls_client_auth`. (As far as I know, the other side uses Spring Authorization Server)

```json
{
  "issuer": "https://issuer",
  "authorization_endpoint": "https://issuer/oauth/authorize",
  "token_endpoint": "https://issuer/oauth/token",
  "token_endpoint_auth_methods_supported": [
    "client_secret_basic",
    "client_secret_post",
    "client_secret_jwt",
    "private_key_jwt",
    "tls_client_auth",
    "self_signed_tls_client_auth"
  ],
  "jwks_uri": "https://issuer/.well-known/jwks.json",
  "userinfo_endpoint": "https://issuer/api/v1/openid/userinfo",
  "response_types_supported": [
    "code"
  ],
  "grant_types_supported": [
    "authorization_code"
  ],
  "code_challenge_methods_supported": [
    "S256"
  ],
  "tls_client_certificate_bound_access_tokens": true,
  "subject_types_supported": [
    "public"
  ],
  "id_token_signing_alg_values_supported": [
    "RS256"
  ],
  "scopes_supported": [
    "openid",
    "profile"
  ],
  "acr_values_supported": [
    "-1",
    "0",
    "1",
    "2",
    "3"
  ],
  "display_values_supported": [
    "page"
  ]
}
```

Then configure the OpenID integration:
```yaml
micronaut:
  security:
    oauth2:
      callback-uri: /api/v1/user/auth/callback
      clients:
        issuer:
          client-id: ${id}
          client-secret: ${secret}
          openid:
            issuer: https://issuer
```

Then, trigger the flow by calling any endpoint that needs authentication.
The redirect and login on the IDP will work, when the callback is opened the server will throw an error.

### Version

4.5.0

**Comment by sdelamo** [comment]
This should be fixed in Micronaut Security 4.10.1
