### ISSUE TITLE
Add support to configure JWKSet cache 

### ISSUE THREAD

**Issue by linthar** [micronaut-projects/micronaut-security#179]
**ENVIRONMENT**
Micronaut Security 1.3.0

**CLASS WITH THE PROBLEM:**
io.micronaut.security.token.jwt.signature.jwks.JwksSignature

**DESCRIPTION**

  The problem is with those two methods code
 ```
    private Optional<JWKSet> getJWKSet() {
        if (jwkSet == null) {
            this.jwkSet = loadJwkSet(getUrl());
        }
        return Optional.ofNullable(jwkSet);
    }
 ```

 ```
    protected List<JWK> matches(SignedJWT jwt, @Nullable JWKSet jwkSet, int refreshKeysAttempts) {
        List<JWK> matches = Collections.emptyList();
        if (jwkSet != null) {
            JWKMatcher.Builder builder = new JWKMatcher.Builder();
            if (keyType != null) {
                builder = builder.keyType(keyType);
            }
            String keyId = jwt.getHeader().getKeyID();
            if (keyId !=null) {
                builder = builder.keyID(keyId);
            }

            matches = new JWKSelector(builder.build()).select(jwkSet);
        }
        if (refreshKeysAttempts > 0 && matches.isEmpty()) {
            return matches(jwt, getJWKSet().orElse(null), refreshKeysAttempts - 1);
        }
        return matches;
    }
 ```

  Once the cache was initilized (this.jwkSet == null) if SignedJWT uses a key (not cached already) authentication will keep failing until JVM restart.

  matches() method will try using keys in cache (jwkSet), if the are no matches, this code will retry the match.

 ```
        if (refreshKeysAttempts > 0 && matches.isEmpty()) {
            return matches(jwt, getJWKSet().orElse(null), refreshKeysAttempts - 1);
        }
 ```

  But the jwkSet will never be reset, because this.jwkSet != null, and  getJWKSet() will always return the same key set: 
 ```
        return Optional.ofNullable(jwkSet);
 ```
the already cached... instead of a new one created with loadJwkSet():

**A POSSIBLE SOLUTION**
    
  A quick and dirty solution could be to set as null the this.jwkSet before retry match()

 ```
    protected List<JWK> matches(SignedJWT jwt, @Nullable JWKSet jwkSet, int refreshKeysAttempts) {
        ...
        }
        if (refreshKeysAttempts > 0 && matches.isEmpty()) {
            this.jwkSet = null; // will force to reset cache
            return matches(jwt, getJWKSet().orElse(null), refreshKeysAttempts - 1);
        }
        return matches;
 ```

**Comment by ikovalyov** [comment]
we have this issue as well

**Comment by linthar** [comment]
Hi Illia:

 I have implemented a workaround (it's an ugly patch until this bug is fixed)

 I have added a second matcher called "JwksSignatureTwo" that is a copy/paste of JwksSignature but with the clean cache fix (line 193):
[ It's a full copy/paste because jwkSet is private]
 

```

if (refreshKeysAttempts > 0 && matches.isEmpty()) {
    LOG.info("Reset jwkSet cache");
    this.jwkSet = null; // force reload jwkSet (JWKs cache could be outdated)
    return matches(jwt, getJWKSet().orElse(null), refreshKeysAttempts - 1);
}
return matches;

```



 this second matcher will be called when the original JwksSignature fails,


 It's ugly but works!

**Comment by jameskleeh** [comment]
I'm going to implement the clearing of the cache on failure. Rather than introduce additional complication and documentation surrounding expiration, this seems like an easy fix that will work for most folks. If there is a need for this type of feature in the future, a new ticket can be created.
