### ISSUE TITLE
Using Micronuat 1.3.1 causes nullable Authentication parameter in controller method to be null regardless of login status

### ISSUE THREAD

**Issue by developerSid** [micronaut-projects/micronaut-security#180]
Ran across an issue when I was upgrading to Micronaut 1.3.1 this week where any controller method that takes a nullable __io.micronaut.security.authentication.Authentication__ is always null.  This is null regardless of the user being logged in or not.  This issue does not exist when using Micronaut 1.3.0

I created a simple project to illustrate my problem located here -> https://github.com/developerSid/tech-garymyers-micronaut-security  I have two branches
1. master
   1. this branch is using Micronaut 1.3.0 and works
2. broken
   1. this branch is using Micronaut 1.3.1 and doesn't work

The example app above is pretty simple.  It provides a controller that just echos the logged in user's username.  The configuration is pretty close to what I have coded in my "real" application, but wanted to distill this down to better illustrate my issue. I created it using the Micronaut cli tool and it ran it using Java 8 via AdoptOpenJDK\jdk-8.0.242.08-openj9 on Windows 10.

I'm using Kotlin as my primary language for developing my application.

Thanks for your time
Gary

**Comment by graemerocher** [comment]
Can you try the just released 1.3.2?

**Comment by developerSid** [comment]
Tried it, and the problem went away.  I should have waited one more release :(

Thanks for getting back to me!
