### ISSUE TITLE
Setting state parameter in oauth2 flow

### ISSUE THREAD

**Issue by swampie** [micronaut-projects/micronaut-security#1806]
### Issue description

Hello,
we are facing an issue while implementing auth0: the frontend is using the react auth0 sdk to set an additional state param for  later redirect. While reading the auth0 documentation it looks like auth0 encrypt the state content during the flow so the StateJsonDeser after decoding the base64 string receives an unparseable bytes array.

I am wondering if there is a micronaut security suggested way of setting the state in the backend rather than the frontend that will allow the callback to receive it and parse it correctly

Thanks

**Comment by swampie** [comment]
I managed to solve this by extending `DefaultStateFactory`

**Comment by sdelamo** [comment]
The docs are here https://micronaut-projects.github.io/micronaut-security/latest/guide/#state
