### ISSUE TITLE
Duplicate Classes in Micronaut Security 4.9.0

### ISSUE THREAD

**Issue by uulyar** [micronaut-projects/micronaut-security#1822]
### Expected Behavior

There should only be one class serving the role of reading tokens from cookies. Either TokenCookieTokenReader or CookieTokenReader should be retained to avoid redundancy and potential conflicts.

### Actual Behaviour

Both **TokenCookieTokenReader** and **CookieTokenReader** exist in the same package with similar functionality, creating redundancy and potential confusion.

### Steps To Reproduce

Add the micronaut-security dependency, version 4.9.0, to your Micronaut project.
Check the package structure or attempt to reference io.micronaut.security.token.cookie classes.
Observe the existence of both TokenCookieTokenReader and CookieTokenReader.

### Version

4.9.0

**Comment by sdelamo** [comment]
Closed via https://github.com/micronaut-projects/micronaut-security/pull/1802
