### ISSUE TITLE
Document SSL with LDAP

### ISSUE THREAD

**Issue by apellegr06** [micronaut-projects/micronaut-security#184]
Hello,

I need to use ldap in a secured way with ldaps and port 636 and certificate but I don't know how to do that with micronaut lib.

Currently I have a yaml section like that configured on an ldap server without security and it works fine :

  security:
    enabled: true
    ldap:
      default:
        context:
          server: 'ldap://myserver_host:389'
          managerDn: 'uid=toto,ou=tutu,dc=tata,dc=fr'
          managerPassword: 'titi'
        search:
          base: 'dc=tutu,dc=fr'
        groups:
          enabled: true
          base: 'ou=group,dc=tutu,dc=fr'

I think I need to change the server to "ldaps://server_host:636" but I don't know where to set parameters for the SSL certificate.

Does someone can help me ?

Thank you
Alain

**Comment by jameskleeh** [comment]
You have to configure it via the Java system properties for SSL


Check out Spring LDAP documentation for connecting to LDAP server over HTTP(S):

As far as self signed certificate is concerned, you can import certificate chain into a truststore and set the following VM arguments:

```
-Djavax.net.ssl.trustStore="<path to truststore file>"
-Djavax.net.ssl.trustStorePassword="<passphrase for truststore>"
```

**Comment by apellegr06** [comment]
Hello,

Thank you for the answer, but it's not the truststore that I must used, but it's a keystore.
So I have added that to the start command :

-Djavax.net.ssl.keyStore="<path to keystore file>"
-Djavax.net.ssl.keyStorePassword="<passphrase for keystore>"

And also configure the ldaps url, but it doesn't work.

When I try to log on ldap, it append nothing.

Regards
