### ISSUE TITLE
Using LDAP authentication with sAMAccountName

### ISSUE THREAD

**Issue by hdjur** [micronaut-projects/micronaut-security#187]
Hi,

I am constantly getting "User not found" when trying to authenticate with AD, tried to use both ports 389 or 3268, the result is same. But I don't know how to specify user search filter for sAMAccountName. Is it possible with micronaut at all, and if so, could you provide an example of configuration?

**Comment by jameskleeh** [comment]
The search filter can be whatever you like https://micronaut-projects.github.io/micronaut-security/latest/guide/#io.micronaut.configuration.security.ldap.configuration.LdapConfiguration$SearchConfiguration. In the future, please ask questions in [Gitter](https://gitter.im/micronautfw)
