### ISSUE TITLE
DelegatingAuthenticationProvider Compares Plaintext password

### ISSUE THREAD

**Issue by Arevico** [micronaut-projects/micronaut-security#188]
When following the guide: https://guides.micronaut.io/micronaut-database-authentication-provider-groovy/guide/index.html, `BCryptPasswordEncoderService.encode` never get's called, instead, BCryptPasswordEncoderService get send the plaintext password as entered by the user.

Fix:

Replace
```java
            if (!passwordEncoder.matches(authenticationRequest.getSecret().toString(), user.getPassword())) {
                return Flowable.just(new AuthenticationFailed(AuthenticationFailureReason.CREDENTIALS_DO_NOT_MATCH));
            }
````

With
```java
            if (!passwordEncoder.matches(delegate.encode(authenticationRequest.getSecret().toString()), user.getPassword())) {
                return Flowable.just(new AuthenticationFailed(AuthenticationFailureReason.CREDENTIALS_DO_NOT_MATCH));
            }
````

**Comment by jameskleeh** [comment]
@Arevico That is how it should be. The bcrypt encoder compares a raw password with an encoded one. The `authenticationRequest.getSecret()` is the raw one and `user.getPassword()` is the encoded one.
