### ISSUE TITLE
DefaultOpenIdClient onCallback() error handling

### ISSUE THREAD

**Issue by jzuijlek** [micronaut-projects/micronaut-security#198]
When a user cancels an OpenID login request, or when an error occurs at the OpenID provider side, the **DefaultOpenIdClient** just dump an **AuthorizationErrorResponseException**.

For example: **oauth/callback/openid-provider?error=access_denied....**

We should be able to catch that exception and handle it ourselves.

As a temporary solution I've tried extending the **DefaultOpenIdClient** to override the **onCallback()** method, but without success.

**Comment by jameskleeh** [comment]
@jzuijlek You can create an `ExceptionHandler<AuthorizationErrorResponseException>` to control the response
