### ISSUE TITLE
Add support for OpenID Connect (OIDC)

### ISSUE THREAD

**Issue by goeh** [micronaut-projects/micronaut-security#2]
It would be nice if Micronaut supported OIDC compliant flows out of the box. That would make it easy to use external identity providers like Auth0 and Okta for authentication in Micronaut services.

OIDC Client support is priority 1, but it's also important to be able to create compliant authorization servers with Micronaut that expose public RSA keys (JWKS) for resource servers to use for signature checks.

> OpenID Connect 1.0 is a simple identity layer on top of the OAuth 2.0 protocol. It allows Clients to verify the identity of the End-User based on the authentication performed by an Authorization Server, as well as to obtain basic profile information about the End-User in an interoperable and REST-like manner.

References:
https://auth0.com/blog/navigating-rs256-and-jwks/
https://connect2id.com/products/nimbus-jose-jwt/examples/validating-jwt-access-tokens
https://connect2id.com/products/nimbus-jose-jwt/examples/jwk-selectors

**Comment by jameskleeh** [comment]
OpenID is supported
