### ISSUE TITLE
Rename micronaut.security.oauth2.authorization.scopes to micronaut.security.oauth2.scopes

### ISSUE THREAD

**Issue by graemerocher** [micronaut-projects/micronaut-security#21]
I’d recommend getting rid of the “authorization” key and just using “scopes”. 

Section https://guides.micronaut.io/micronaut-oauth2-okta/guide/index.html#oauth2

**Comment by jameskleeh** [comment]
its now `micronaut.security.oauth2.clients.*.scopes`
