### ISSUE TITLE
Does micronaut closes the connection when the JWT expires?

### ISSUE THREAD

**Issue by phxql** [micronaut-projects/micronaut-security#214]
Hi,

I have a strange problem. We have JWT access tokens which expire after 1 minute. We also have long-running requests which take longer than 1 minute to complete. At the exact same time the JWT expires, the client gets a `ClosedChannelException`. Is Micronaut closing the connection when the JWT expires? If so, can this be disabled?

Thanks!

**Comment by sdelamo** [comment]
> Is Micronaut closing the connection when the JWT expires? If so, can this be disabled?

No, we are not. 

JWT validation is performed when you go through [SecurityFilter](https://github.com/micronaut-projects/micronaut-security/blob/1.3.x/security/src/main/java/io/micronaut/security/filters/SecurityFilter.java). In particular, the JWT is validated by [JwtTokenValidator](https://github.com/micronaut-projects/micronaut-security/blob/1.3.x/security-jwt/src/main/java/io/micronaut/security/token/jwt/validator/JwtTokenValidator.java)

Could you create a sample app which reproduces your issue?

**Comment by phxql** [comment]
Okay, thanks for the clarification - I will check the other components in my setup, maybe they close the connection. I'll reopen the ticket if I suspect the culprit in micronaut.

**Comment by sdelamo** [comment]
thanks @phxql  sorry for not being of more help.

**Comment by phxql** [comment]
Yeah, no problem - I have read through the SecurityFilter code and haven't found anything. Just wanted to make sure that you as the developers don't have something in there I just didn't find :)
