### ISSUE TITLE
Add SameSite property to JwtConfigurationProperties

### ISSUE THREAD

**Issue by abedurftig** [micronaut-projects/micronaut-security#217]
After this https://github.com/micronaut-projects/micronaut-core/pull/2956, it should be possible to configure the SameSite setting via the application properties.

**Comment by jameskleeh** [comment]
The security classes inherit from the ones changed in core so nothing to do on our end except compile with that version of core

**Comment by abedurftig** [comment]
@jameskleeh, there is some work. The `JwtConfigurationProperties` need to updated, like I have shown in the PR or do I miss something?
