### ISSUE TITLE
Default Keycloak algorithm (HS256) reported as not supported.

### ISSUE THREAD

**Issue by jasondlee** [micronaut-projects/micronaut-security#22]
It's hard to say whether or not this is a valid issue, so I'll describe what I did and saw, and let you make the call. :)

In a nutshell, I took the Okta OAuth2 example and tried to configure it to use Keycloak. On the demo side, I made this change to application.yml:
```    security:
        enabled: true # <1>
        oauth2:
            client-secret: '${OAUTH_CLIENT_SECRET:""}' # <2>
            client-id: 'examples' # <3>
            #issuer: '${OIDC_ISSUER_DOMAIN}/oauth2/${OIDC_ISSUER_AUTHSERVERID}' # <4>
            issuer: "http://localhost:8080/auth/realms/micronaut-demo"
```
I set the following environment variables:
```
export KEYCLOACK_DOMAIN=http://localhost:8080
export KEYCLOAK_REALM=micronaut-demo
```
On the Keycloak side, I created a realm, `micronaut-demo`, leaving everything as the default, iirc (I was following their getting started guide).

I started the micronaut application (in debug mode) and would get NPEs after authentication, which seemed really odd (especially since the debug session didn't seem to show any nulls) on this line of code (DefaultIdTokenAccessTokenResponseHandler line 62):
```
throw new InvalidIdTokenAccessTokenResponseException(idTokenAccessTokenResponse);
```
After stepping in to the call to `idTokenAccessTokenResponseValidator.validate`, I found that Micronaut was claiming that HS256 was not a supported algorithm (`JwtTokenValidator.validateSignedJWTSignature`). Putting a breakpoint at `JwksSignatureFactory.jwsk`, it looks like HS256 was in the list of supported algorithms, but by the time `SignatureConfiguration` was injected into `JwtTokenValidator`, the only thing that seemed to be listed was RS256. 

To make authentication work correctly, I had to modify realm in Keycloak to use RS256 by default (http://localhost:8080/auth/admin/master/console/#/realms/micronaut-demo/token-settings for reference). Once I made that change, I was able to authenticate against Keycloak and successfully redirect back to the app, but something seems strange about that.

If there are any more details you need (modified local sources, keycloak realm export, etc.), don't be shy. :)

**Comment by jameskleeh** [comment]
I can confirm with the latest snapshot I can authenticate with keycloak using default settings. Please let me know if that is not the case and I'll reopen

**Comment by jasondlee** [comment]
I'm trying to verify now, but this class no longer compiles: https://github.com/micronaut-guides/micronaut-oauth2-okta/blob/master/complete/src/main/java/example/micronaut/DefaultStateProvider.java

Is there a better/more up-to-date example I can work from?

**Comment by jameskleeh** [comment]
@jasondlee The guide needs updated and its on our todo. The import just needs changed

**Comment by jasondlee** [comment]
I assumed as much, but I haven't been able to find where the class was moved to. Or what took over the functionality. Or whatever. :) I have micronaut-oauth2 cloned and up-to-date, and the only place I can find StateProvider mentioned is in a couple of Groovy files.

**Comment by jameskleeh** [comment]
Its in this repository now `micronaut-projects/micronaut-security`. Sorry the name also changed. It's here https://github.com/micronaut-projects/micronaut-security/blob/master/security-oauth2/src/main/java/io/micronaut/security/oauth2/endpoint/authorization/state/StateFactory.java

**Comment by jasondlee** [comment]
Ah! OK. I think I have everything fixed up (it's compiling at least). I'll try to validate as quick as I can, but it's going to have to wait until tomorrow. :)
