### ISSUE TITLE
Auth0EndSessionEndpoint mangles URLs

### ISSUE THREAD

**Issue by ronhitchens** [micronaut-projects/micronaut-security#221]
I observed that the URL location returned from the Auth0 EndSession handler was malformed, which caused OAuth logout operations to not work properly.  The URL I saw in the redirect response was:

`https:/mydomain.com/v2/logout`

Note the single slash after https.  

After much digging into the Micronaut code, I determined that the URL being generated in `Auth0EndSessionEndpoint.getUrl()` was the source of the problem.  The configured Auth0 issuer URL was correct: `https://mydomain.com`.

A quick test showed that `StringUtils.prependUri()` was the culprit (in Groovy):

```
static void main (String[] args) {
	println StringUtils.prependUri ('https://mydomain.com', '/v2/logout')
}
```

Yields:

`https:/mydomain.com/v2/logout`

Of course it should be:

`https://mydomain.com/v2/logout`

That's some broken code right there.

My IDE tells me that there are eight places where `StringUtils.prependUri` is called, including `DefaultHttpClient`, which is a bit worrying.

### Environment Information

- **Operating System**: MacOs / AWS Linux
- **Micronaut Version:** 1.3.4
- **JDK Version:** 1.8

**Comment by graemerocher** [comment]
I never implied you misused the API it is indeed a bug and thanks for the report. I would encourage you to communicate with Open Source maintainers in a less passive aggressive tone however. Also PRs welcome.

**Comment by ronhitchens** [comment]
Hmm.  When I clearly describe a problem, with an example, and point at the exact place where the bug exists, and you reply with:

> The method is designed to work on paths not full URIs. Looking for usages the only place it seems to be being incorrectly used is prependContextPath in DefaultHttpClient and only when a context path is set.

That sure seems like you're telling me I'm wrong and there is no bug.  If I misunderstood what you meant to say, I apologize for that.  I would encourage you to communicate with Bug Reporters in less ambiguous language.

Thank you.
