### ISSUE TITLE
LoginSuccessfulEvent is invoked twice when using OAuth security

### ISSUE THREAD

**Issue by pditommaso** [micronaut-projects/micronaut-security#223]
I've noticed that the `LoginSuccessfulEvent` is invoked twice when using MN OAuth security module once before the LoginHandler and the second time after. 

It should be added that I'm using a custom `RedirectingLoginHandler`. 

MN version 1.3.4.

**Comment by jameskleeh** [comment]
@pditommaso Are you using the password grant? Can you upload an example that reproduces the issue? I can see the event is emitted in the login controller and the callback of the oauth controller. I can't envision a case where both of those methods are called for a single login

**Comment by pditommaso** [comment]
I've realised there's a problem in my login flow. Closing. Tx!
