### ISSUE TITLE
Pattern or provide override for additional Login info in Login controller

### ISSUE THREAD

**Issue by StephenOTT** [micronaut-projects/micronaut-security#228]
MN 1.3.4

Using LoginController, you are provided with username/password credentials using UsernamePasswordCredentials.class.

If additional info should be provided (such as Tenant, or other principal attributes), Is it better to replace the LoginController?  Or should LoginController provide the functionality to configure the Login body?
https://github.com/micronaut-projects/micronaut-security/blob/1.3.x/security/src/main/java/io/micronaut/security/endpoints/LoginController.java#L82

**Comment by jameskleeh** [comment]
@StephenOTT The body type can't be configurable because a static type has to be in place for the method. If you need additional information, the solution is to override the controller

**Comment by StephenOTT** [comment]
Thank you
