### ISSUE TITLE
No way of signalling invalid refresh tokens

### ISSUE THREAD

**Issue by Fuyukai** [micronaut-projects/micronaut-security#229]
In a RefreshTokenPersistence, `getUserDetails` can only ever return a valid UserDetails; failing to do so causes a 500 errror with `The source Publisher is empty`. There should be a way to return a 401/403/whatever if the refresh token is invalid in some way.

**Comment by jameskleeh** [comment]
> In a RefreshTokenPersistence, getUserDetails can only ever return a valid UserDetails;

That isn't true. It can return a publisher than emits an exception
