### ISSUE TITLE
Redirect user back to the page where they started, after authentication

### ISSUE THREAD

**Issue by mikaelhg** [micronaut-projects/micronaut-security#23]
When users enter a OAuth2-secured application through a link to a particular page or resource, they expect to continue using the application from that page, after having gone through authentication, rather than to be redirected to the application root URL.

This is how Spring OAuth2 behaves, as well as most authentication schemes I'm aware of.

Please implement this in micronaut-oauth2, and tell us roughly how we should devise a future-proof workaround, while waiting for the feature.

**Comment by jameskleeh** [comment]
micronaut-oauth2 was reworked to use more of the existing infrastructure of micronaut-security and thus this feature needs reimagined in a way that will work for all authentication use cases

**Comment by mikaelhg** [comment]
While waiting for the reworking, how would you recommend we work around this issue?

**Comment by sdelamo** [comment]
@jameskleeh this is implemented right?

**Comment by jameskleeh** [comment]
Yes

**Comment by mikaelhg** [comment]
Unfortunately, I'm unable to verify the solution and close the ticket, as I no longer have that component at hand.
