### ISSUE TITLE
Authorization header prefix treated case-sensitive

### ISSUE THREAD

**Issue by jcassee** [micronaut-projects/micronaut-security#252]
The implementation of `HttpHeaderTokenReader.extractTokenFromAuthorization` [treats the header value prefix as case sensitive](https://github.com/micronaut-projects/micronaut-security/blob/987e3d3c1962c1152dc74eaeed0bdba2e48cbc81/security/src/main/java/io/micronaut/security/token/reader/HttpHeaderTokenReader.java#L74). Although [the OAuth spec seems to suggest that is it](https://tools.ietf.org/html/rfc6750#section-2.1), [the HTTP spec says that this prefix is a case insensitive token](https://tools.ietf.org/html/rfc7235#section-2.1).

Can the check for the prefix be made to be case-insensitive? (I can submit a PR is that is useful.)

**Comment by sdelamo** [comment]
We currently support: 

`Bearer xx.yy.zz => xx.yy.zz `

and you want to support as well:

`bearer xx.yy.zz => xx.yy.zz`

right?

**Comment by sdelamo** [comment]
And of course PRs are welcomed.

**Comment by jcassee** [comment]
@sdelamo Yes, all lower-case is my immediate use case, but "BeArEr" is also valid.

I'll create a PR. I see there are no immediate tests for this class. Do you want me to create one? If so, what would be a good location?

**Comment by sdelamo** [comment]
> I'll create a PR. I see there are no unit tests for this class. Do you want me to create a test? If so, what would be a good location?

You will see many places int he framework where we don't have unit tests but the class is tested in a functional tests which engages the bean. 

However, it is great that you added the functional test.
