### ISSUE TITLE
Mistake in the Documentation, Section CustomClaimSetGenerator Guide

### ISSUE THREAD

**Issue by hydroid7** [micronaut-projects/micronaut-security#253]
The [example](https://micronaut-projects.github.io/micronaut-security/2.0.0.M1/guide/index.html#claimsGeneration) uses `@Singleton` annotation for the custom claim set generator. 
However, the Bean is initialized lazy and there is no `ClaimSetGenerator` Bean in the context when required. This causes an error and the injection fails.

The issue can be fixed when using  `@Context` instead of `@Singleton` in file:

https://github.com/micronaut-projects/micronaut-security/blob/c78b95fb9f0e3f5cd35debd253c88e4c049ca471/security-jwt/src/test/groovy/io/micronaut/docs/jwtclaimsoverride/CustomJWTClaimsSetGenerator.java#L18

**Comment by sdelamo** [comment]
Hi @hydroid7 Not sure I understand the problem. I think @Singleton is the correct scope for the replacement. Please, provide an example app which reproduces the issue.
