### ISSUE TITLE
Ability to set the token expiration time dinamically.

### ISSUE THREAD

**Issue by ovargas** [micronaut-projects/micronaut-security#255]
I'm currently in the middle of my custom implementation of client_credentials and grant_type, I have achieved it by implementing:
1. CustomLoginController
2. CustomAuthenticationRequest to include identity (client_id), secret, username, password and grant type.
3. CustomAuthenticationProvider

I would like to be able to set a different token expiration time per client_id, so far setting `exp` in UserDetails attribute seems to work, but it is working because `JWTClaimsSetGenerator` first set the `exp` based on the configuration and then overwrite it with the values in `UserDetails` attributes. 

Additionally, even if this hack could work for me today, still the `TokenRender` displays the configured expiration.

I'm using Micronaut 2.0.0.M3 and M. Security 2.0.0.BUILD-SNAPSHOT

**Comment by sdelamo** [comment]
You could create a bean replacement for `AccessRefreshTokenGenerator`, the bean responsible of generating the expiration.

Probably something like: 

```
@Singleton
@Replaces(AccessRefreshTokenGenerator.class)
CustomAccesRefreshTokenGenerator extends DefaultAccessRefreshTokenGenerator {

@Override
@NonNull
    public Integer accessTokenExpiration(@NonNull UserDetails userDetails) {
// your custom impl
    }

    @Override
    @NonNull
    public Integer accessTokenExpiration(@NonNull Map<String, ?> oldClaims) {
// your custom impl
    }
    
}
```

**Comment by sdelamo** [comment]
see: https://github.com/micronaut-projects/micronaut-security/commit/8f37763d002c1d1727e88ed5c0290c6840267acc
