### ISSUE TITLE
TokenCookieConfiguration not being loaded

### ISSUE THREAD

**Issue by sdelamo** [micronaut-projects/micronaut-security#270]
See annotated tests with `@PendinFeature` in reference comment

**Comment by graemerocher** [comment]
The update to the build picked up that some tests were seemingly not being run and there are failures that depend on this issue before #268 can be merged

**Comment by sdelamo** [comment]
I've merged #268 However, we still ned to fix test flagged with `@PendingFeature` at https://github.com/micronaut-projects/micronaut-security/commit/0af75498ae29740660584be760c0e6c33c4d3617
