### ISSUE TITLE
Micronaut Security JWT guide references 2.0.0.BUILD-SNAPSHOT and classes not available in any stable release

### ISSUE THREAD

**Issue by franz-see** [micronaut-projects/micronaut-security#271]
The guide https://guides.micronaut.io/micronaut-security-jwt/guide/index.html

Classes not available in any stable release
 * OauthErrorResponseException
 * IssuingAnAccessTokenErrorCode

And there are no other micronaut security jwt guide except this one

**Comment by sdelamo** [comment]
I've included link to 1.x guide in the top of the guide: 

https://guides.micronaut.io/1.x/micronaut-guides/micronaut-security-jwt/index.html
