### ISSUE TITLE
The Micronaut JWT Authentication guide's UnsignedRefreshTokenSpec does not hit CustomRefreshTokenPersistence

### ISSUE THREAD

**Issue by franz-see** [micronaut-projects/micronaut-security#272]
I was reading this guide - https://guides.micronaut.io/micronaut-security-jwt/guide/index.html
And I cloned this project - https://github.com/micronaut-guides/micronaut-security-jwt

1. I loaded up the project's `complete` directory into my IDE
2. I added break points to `example.micronaut.CustomRefreshTokenPersistence#persistToken()` and to `example.micronaut.CustomRefreshTokenPersistence#getUserDetails()`
3. I ran `UnsignedRefreshTokenSpec` in debug mode.

Expectation: 
Breakpoints in `CustomRefreshTokenPersistence` should have been hit

Actual:
Breakpoints in `CustomRefreshTokenPersistence` were never hit. 

Interestingly enough
a) If I delete the body of `CustomRefreshTokenPersistence`'s `persistToken()` and `getUserDetails()`, the test still passes
b.) If I delete `CustomRefreshTokenPersistence` itself, the test fails.

Looks like `CustomRefreshTokenPersistence` just needs to exist regardless of the implementation

**Comment by jameskleeh** [comment]
That test simply tests the failure case of submitting an invalid token. Only if the token is valid does it get passed to the token persistence layer
