### ISSUE TITLE
JWT's cookie and bearer are mutually exclusive

### ISSUE THREAD

**Issue by morki** [micronaut-projects/micronaut-security#275]
When setting both `security.token.jwt.cookie.enabled` and `security.token.jwt.bearer.enabled` to `true`, only bearer token is returned from `/login` endpoint.

It would be helpful, if both are used, so bearer token is returned and cookie is set.

For example, for web application, the browser will use cookie and ignore the bearer response, but mobile app will ignore cookie and use bearer instead.

Is it use case, that should be enabled, or am I missing something?

Thanks for your response.

**Comment by jameskleeh** [comment]
I don't think we will be supporting this. We already support a wide array of use cases and this would only complicate matters further. You could achieve this by overriding the login handler to also add a cookie.
