### ISSUE TITLE
Delete UserDetails and just use Authentication

### ISSUE THREAD

**Issue by sdelamo** [micronaut-projects/micronaut-security#282]
I think one of the more confusing parts of the security API is the use of `UserDetails`, an implementation, instead of `Authentication` the interface. 

The correct way to instantiate a `UserDetails` should be 

```java
new UserDetails('john', ['ROLE_USER'], [tokenConfiguration.getRolesName(): ['ROLE_USER'], [tokenConfiguration.getNameKey(): `john`)
```

and then we should be able to expose a `getAttributes()` method in `UserDetails`. 

Initially `UserDetails` did not have attributes. Moreover, the above instantiation is cumbersome. What we did is don't expose `getAttributes()` and expose 

```public Map<String, Object> getAttributes(String rolesKey, String usernameKey)``` instead. 

So, to go from `UserDetails` to `Authentication` you will do something like: 

```java
UserDetails userDetails = new UserDetails('john', ['ROLE_USER'])
new Authentication() {
   @Override
   String getName() {
       userDetails.getName()
   }
   
   Map<String, Object> getAttributes() {
      [tokenConfiguration.getRolesName(): userDetails.getRoles(), [tokenConfiguration.getNameKey(): userDetails.getUsername())
   }
}
``

which is a pretty hacky.

**Comment by katoquro** [comment]
Hello! Initially I wanted to ask a question like "We have username in our system optional and we relay on id and email so how we should manage UserDetails?". Currently I see that this PR should solve my problem and we won't see usage and casting to user details in security classes.

How long does it take to release this PR? 
Thanks

P.S.
Currently we put "user id" at "username" like a workaround and sometimes it may be confusing )

**Comment by sdelamo** [comment]
This is a breaking change. So it will go in the next mayor version of Micronaut Security. That it is to say. It may take several weeks go to be released.
