### ISSUE TITLE
Extending and replacing SecurityFilter makes the UserPrincipal non-injectable

### ISSUE THREAD

**Issue by fmayoral** [micronaut-projects/micronaut-security#292]
Because of how the [PrincipalArgumentBinder](https://github.com/micronaut-projects/micronaut-security/blob/1.3.x/security/src/main/java/io/micronaut/security/authentication/PrincipalArgumentBinder.java#L45) works, extending the SecurityFilter breaks the injection of the user principal if the extending class is named anything else other than `SecurityFilter`.
This looks intentional, however it's rather obscure and it's not documented how to get around this.

### Task List

- [  x  ] Steps to reproduce provided
- [n/a] Stacktrace (if present) provided

### Steps to Reproduce

1. Extend the SecurityFilter with a class named anything other than 'SecurityFilter'
2. Create a basic endpoint that receives the user principal or authentication as an argument
3. Verify the argument is null

### Expected Behaviour

The user principal can be injected as a parameter.

### Actual Behaviour

The user principal parameter is unresolved.

**Comment by jameskleeh** [comment]
@fmayoral The binder needs to know whether filters have been executed yet or not. There isn't a standard way in Micronaut to determine that so we are using the request attribute for SecurityFilter. You can still extend the class, however you would have to set that attribute in order for that logic to work.
