### ISSUE TITLE
Support opaque Bearer token with OAuth 2.0 Token Introspection

### ISSUE THREAD

**Issue by lightoze** [micronaut-projects/micronaut-security#3]
When access token is opaque (which is assumed by OpenID Connect spec) it can be validated by resource server using token introspection endpoint.

https://tools.ietf.org/html/rfc7662

Related to #650

**Comment by jameskleeh** [comment]
@lightoze Can you clarify what you're asking for here?

**Comment by lightoze** [comment]
@jameskleeh I mean being able to validate non-JWT OAuth 2.0 Bearer tokens. You can get a quick idea by reading https://www.oauth.com/oauth2-servers/token-introspection-endpoint/

**Comment by jameskleeh** [comment]
Yeah I’m familiar with the endpoint. What functionality from this library
are you expecting in regards to it?

**Comment by lightoze** [comment]
@jameskleeh This is about creating OAuth resource server with Micronaut. Incoming token from the client needs to be validated which is already doable for JWT but in my case given authorization server uses opaque access tokens and you're supposed to make a request from resource server to validate it.
What I'm expecting is being able to configure Micronaut as a resource server, that is.

**Comment by jameskleeh** [comment]
Understood. That would be your responsibility to do in the user details
mapper. I’ll see about making it easy to do

**Comment by lightoze** [comment]
Also it will be quite important to be able to cache token introspection response for performance reasons.

**Comment by jameskleeh** [comment]
@lightoze Why would it make sense to be cached? The use case you're referring to is a once per login action

**Comment by lightoze** [comment]
@jameskleeh Sorry if I'm not communicating it clearly but the use case is about access token validation at (normally) stateless resource server side, so the token is validated on every request and there's no session whatsoever.

**Comment by jameskleeh** [comment]
@lightoze If the token will be validated on the serve (Oauth provider), why do you want to duplicate every call to the provider with an introspection call to validate it ahead of time?

**Comment by lightoze** [comment]
@jameskleeh Because custom authorization server is a part of our own deployment and my service is a part of "Oauth provider" you're referring to. So when a request comes to my service from a client it should:
1. fetch Bearer authentication token from HTTP header
2. fetch token information from authorization server (with JWT this step is unnecessary)
3. validate token validity, scope, etc.

**Comment by jameskleeh** [comment]
@lightoze This library is an OAuth 2.0 and OpenID client, not a server (or provider). So anything that is the responsibility of the provider is out of scope for this library

**Comment by lightoze** [comment]
@jameskleeh It was not very clear at the time I created this feature request :) Also while I can 100% agree that auth server implementation is out of scope and an overkill, resource server support sounds like a very natural fit for this library. Most of the stuff is already there (e.g. token validation once you've got the token).

**Comment by jameskleeh** [comment]
@lightoze So in your case the application is a middleware between a client with an access token and an authorization server that issued the token?

**Comment by lightoze** [comment]
Yes, kind of. It doesn't need authorization server for anything except token introspection, really.

**Comment by jameskleeh** [comment]
@lightoze Are you wanting this library to generate access tokens or just be able to call a remote introspection endpoint?

**Comment by lightoze** [comment]
@jameskleeh Just to call the endpoint, and then process the response in a way similar to current JWT implementation (sans signature checks).

**Comment by chantrybjss** [comment]
I think this is precisely what I am doing in https://github.com/micronaut-projects/micronaut-security/issues/31. Being able to do token validation manually, either as part of the same service or on another service is a pretty important feature. 

I have been able to do it, but having documentation about best practices would be nice. For example, during implementation we have to create an instance of Authentication which returns a map of String to Object, and we are just supposed to know that that map has to have a key of “roles” which points to a value of either a single string or a list of strings. The only current way to figure this out is by reading the source code. I also wonder whether the implementation will change in the future.

**Comment by jameskleeh** [comment]
@chantrybjss I think your information is out of date. Currently a user
details object gets created which has a well defined place to put roles.

I’m not sure what you’re trying to say whether this implementation will
change. The oauth2 part of this module has not gone beyond snapshot so to
expect stability at this point is not reasonable.

**Comment by chantrybjss** [comment]
@jameskleeh Good call on the UserDetails object. I completely missed it when I read through the documentation.

I think you misinterpreted me on the stability point. I have only a basic understanding of micronaut security and I am coming at this with a very specific use case in mind. Essentially, I want to be able to pass a token using an Authorization header to my service. Using this token, I want to be able to go off to another service to get the roles and user attached to the token. I am not interested in oauth2 or even having micronaut manage JWT for me. 

In terms of implementation changes, I am mainly concerned with the AuthenticationFetcher singleton and how I am using it to essentially bypass micronaut. Is this the correct approach?

**Comment by jameskleeh** [comment]
I don’t think a call to a remote service for every api call to your
application is a good thing. That’s before the normal business logic

**Comment by chantrybjss** [comment]
Sadly, that’s not my decision to make. I didn’t design the infrastructure I’m working with.

**Comment by paulbandler** [comment]
This issue describes exactly the use-case I am facing - i.e. a Micronaut resource server receives an opaque bearer access tokens from a (JavaScript/Angular) OpenID client that needs to be validated using the UserInfo endpoint provided by the issuing Identity Service.  @jameskleeh can you please clarify whether this use-case can be implemented with the Micronaut security framework, and if so, which is the relevant section of the guide - 15.3.1.1.2 User Details Mapper?  The sounds ~close but the documentation reads as though it's used within a client, rather than a resource server that has no client context as far as I understand from an incoming Request, and can only assume that the bearer token is recognisable by a single Identity Provider that it presents the bearer token to?

**Comment by jameskleeh** [comment]
@paulbandler Please ask this question in [Gitter](https://gitter.im/micronautfw) or create a [discussion](https://github.com/micronaut-projects/micronaut-core/discussions)

**Comment by nbrugger-tgm** [comment]
@jameskleeh The provided gitter link doesn't work. Is there any way to find information how to set up a micronaut service as a resource server using opaque access tokens?
```mermaid
sequenceDiagram
    participant RS as Micronaut APP
    participant UA as Browser
    participant AU as OAuth Server
    UA ->> AU: Some OAuth/OIC flow
    AU ->> UA: Opaque bearer token (example: GJ73F5CD)
    destroy UA
    UA ->> RS: GET /protected [BEARER: GJ73F5CD]
    RS ->> AU: /introspect [Payload: GJ73F5CD]
    AU ->> RS: 200 [Payload:<Some JWT with claims>]
    note over RS: Processes the JWT (validating, fetching roles, caching ...)
 ```
    in this case Browser is just a generic user agent (mobile device, server side application with session ...).
    
1. How would this be possible to implement myself? `TokenValidator` seems to be a part of it but there i have to validate + parse the JWT myself? Where should a JWT be handed?
2. Is this expected to work with micronaut security or considered a "non-need"?

**Comment by nbrugger-tgm** [comment]
👀 any updates/ideas/solutions/comments? 

Was anything i posted unclear and needs more details?
