### ISSUE TITLE
Session based authentication logout contains original session cookie

### ISSUE THREAD

**Issue by ronane2x** [micronaut-projects/micronaut-security#30]
Invoking the 'logout' endpoint when using the session based authentication results in the same set-cookie session response returned as for a 'login' request. 

Steps to reproduce:
1) Clone the Git repository: git clone https://github.com/micronaut-guides/micronaut-security-session.git
2) Run application
3) Login

Example:
```
$ curl -v -X POST "http://localhost:8080/login" -H  "accept: application/json" -H  "Content-Type: application/json" -d "{\"username\":\"sherlock\",\"password\":\"password\"}"
*   Trying ::1...
* TCP_NODELAY set
* Connected to localhost (::1) port 8080 (#0)
> POST /login HTTP/1.1
> Host: localhost:8080
> User-Agent: curl/7.54.0
> accept: application/json
> Content-Type: application/json
> Content-Length: 45
> 
* upload completely sent off: 45 out of 45 bytes
< HTTP/1.1 303 See Other
< Location: /
< Authorization-Info: a8733442-3124-4b47-8b3a-17986d779365
< set-cookie: SESSION=YTg3MzM0NDItMzEyNC00YjQ3LThiM2EtMTc5ODZkNzc5MzY1; Path=/; HTTPOnly
< Date: Thu, 9 May 2019 14:10:38 GMT
< transfer-encoding: chunked
< connection: close
< 
* Closing connection 0
```

4) Logout (using session from login)

Example:
```
$ curl -v -X POST "http://localhost:8080/logout" -H  "accept: application/json" -H  "Content-Type: application/json" --cookie "SESSION=YTg3MzM0NDItMzEyNC00YjQ3LThiM2EtMTc5ODZkNzc5MzY1"
*   Trying ::1...
* TCP_NODELAY set
* Connected to localhost (::1) port 8080 (#0)
> POST /logout HTTP/1.1
> Host: localhost:8080
> User-Agent: curl/7.54.0
> Cookie: SESSION=YTg3MzM0NDItMzEyNC00YjQ3LThiM2EtMTc5ODZkNzc5MzY1
> accept: application/json
> Content-Type: application/json
> 
< HTTP/1.1 303 See Other
< Location: /
< Authorization-Info: a8733442-3124-4b47-8b3a-17986d779365
< set-cookie: SESSION=YTg3MzM0NDItMzEyNC00YjQ3LThiM2EtMTc5ODZkNzc5MzY1; Path=/; HTTPOnly
< Date: Thu, 9 May 2019 14:11:51 GMT
< transfer-encoding: chunked
< connection: close
< 
* Closing connection 0
```

Expected: Response to logout request should set the session value to something other than the original session id (maybe blank).
Actual: The same session id is returned for the logout request as is for the login request

Environment:
OS: MacOS 10.14.3
JDK: jdk1.8.0_162
Micronaut: 1.1.0 (also updated the guided solution to 1.1.1 and the behaviour was the same)

**Comment by jameskleeh** [comment]
This is the expected behavior. Logging out removes the authentication object from the session, but does not create a new session. Is this causing a problem for you in some way?

**Comment by ronane2x** [comment]
Speaking to @jameskleeh on the gitter channel I understand the behaviour better now. We agreed that if I need to invalidate sessions then this can be customised in the SessionLogoutHandler.

Happy for the issue to be closed.
