### ISSUE TITLE
Document AuthenticationFetcher

### ISSUE THREAD

**Issue by cargillchantry** [micronaut-projects/micronaut-security#31]
I think some documentation is required for users who want to integrate with micronaut security but using custom authentication strategies. 

I pass an Authorization header up to my service and then use it to produce some roles through my own methodology (not important here). My main goal is to use the @Secured annotation to secure my endpoints and handle setting up the security context myself. 

After reading through the source code, I discovered a pretty simple method to do this but it took quite a bit of digging. 

I basically do the following.

```
@Singleton
public class CustomAuthenticationFetcher implements AuthenticationFetcher {
    private final CustomAuthenticationProvider customAuthenticationProvider;

    @Inject
    public CustomAuthenticationFetcher (final CustomAuthenticationProvider customAuthenticationProvider) {
        this.customAuthenticationProvider = customAuthenticationProvider;
    }

    @Override
    public Publisher<Authentication> fetchAuthentication(final HttpRequest<?> request) {
        return request.getHeaders().getAuthorization()
            .map(customAuthenticationProvider::getAuthentication)
            .orElseGet(Flowable::empty);
    }
}
```

Then I simply implement Authentication in CustomAuthentication. 

I essentially have 2 questions. 

1.  Will the above method cause any problems either now or in the likely future?
2.  Am I missing some important documentation somewhere?

**Comment by jameskleeh** [comment]
@chantrybjss 
1. No - that is the supported solution
2. It looks like it isn't documented well or at all, so I don't think so

**Comment by alvarosanchez** [comment]
@cargillchantry as far as I can tell, the default `TokenAuthenticationFetcher` can do what you do.

It uses a `TokenResolver` to resolve a token from the request, which in turn uses `TokenReader`s, and there is already one `TokenReader` implementation that reads it from an HTTP header.

Once the token is found, it will attempt to validate it using any `TokenValidator`s registered. This is the piece where you would write your custom implementation (CustomAuthentication), by implementing the `TokenValidator` interface.
