### ISSUE TITLE
Limit JWT_REFRESH_TOKEN cookie paths

### ISSUE THREAD

**Issue by sdelamo** [micronaut-projects/micronaut-security#331]
@istvanszoboszlai 

> JWT_REFRESH_TOKEN cookie should have it's path set to /oauth/access_token and /logout so that it is not sent with other requests.

@jameskleeh 

> This should be configurable, and if not set, use the configured value for the controller (the controller path is configurable). If that value is not set, use the default for the controller. We need to support those who have either changed the default path, or replaced the controller with their own implementations that we currently don't know what the path is.

**Comment by istvanszoboszlai** [comment]
@sdelamo , did you not mean to quote "JWT_REFRESH_TOKEN cookie should have it's path set to /oauth/access_token and /logout so that it is not sent with other requests." from the umbrella issue of #315?

**Comment by sdelamo** [comment]
@istvanszoboszlai I have updated the issue description.

**Comment by sdelamo** [comment]
Logout path is configurable via [`LogoutControllerConfiguration::getPath()`](https://github.com/micronaut-projects/micronaut-security/blob/master/security/src/main/java/io/micronaut/security/endpoints/LogoutControllerConfiguration.java#L30) and here it is a related test: https://github.com/micronaut-projects/micronaut-security/blob/master/security/src/test/groovy/io/micronaut/security/endpoints/LogoutControllerPathConfigurableSpec.groovy

**Comment by sdelamo** [comment]
Refresh token path is configured via: [OauthControllerConfiguration::getPath](https://github.com/micronaut-projects/micronaut-security/blob/master/security-jwt/src/main/java/io/micronaut/security/token/jwt/endpoints/OauthControllerConfiguration.java#L33). 

It is used in the [OauthController](https://github.com/micronaut-projects/micronaut-security/blob/master/security-jwt/src/main/java/io/micronaut/security/token/jwt/endpoints/OauthController.java#L48)
