### ISSUE TITLE
Logout Handler should also clear JWT_REFRESH_TOKEN cookie and invalidate token

### ISSUE THREAD

**Issue by sdelamo** [micronaut-projects/micronaut-security#332]
@istvanszoboszlai 

> logout handler should also clear JWT_REFRESH_TOKEN

> RefreshTokenPersistence should have a new method `invalidateToken(String refreshToken), and JwtClearingLogoutHandler should call this method by default.

@sdelamo 
> I am not sure about this this method. But probably there is not harm to add it, specially if we want to enforce that behaviour in logout endpoint.

> I see any application using refresh token to need something to revoke refresh tokens. In the guide, what I did was to add a revoked property to the entity used to persist the refresh tokens.

> Just to clarify: You want the /logout endpoint to call invalidate refresh token because if we delete only the access token then when the user visits a secured endpoint, it may redirect to the login endpoint and get a new access token due to the refresh token which was not deleted and thus from the user point of view it will be as if the logout did not work.

@istvanszoboszlai 

> Yes this is exactly the reasoning, which actually happened to me, when I implemented the refresh mechanism. I also think that it is a (not to severe, but) security issue if the user's machine possesses a token that grants access to a system after logging out form that system.

This is a subtask from https://github.com/micronaut-projects/micronaut-security/issues/315

**Comment by matt-snider** [comment]
@sdelamo Any context on the point about `invalidateToken()` and why it wasn't implemented? Is there a recommendation for how to do this? I saw the preceding discussion in #315 but it looks like it was not mentioned again in #397  

> RefreshTokenPersistence should have a new method `invalidateToken(String refreshToken), and JwtClearingLogoutHandler should call this method by default.

**Comment by sdelamo** [comment]
@matt-snider It will depend application. In this example app, https://guides.micronaut.io/latest/micronaut-security-jwt-gradle-java.htmlI am revoking the refresh tokens by flagging them as revoked in the DB. not sure if this helps.

**Comment by jameskleeh** [comment]
@matt-snider The logout handler is only responsible for determining what should be done after a logout. Any refresh token persistence can listen for the `LogoutEvent` and do whatever is appropriate

**Comment by matt-snider** [comment]
@jameskleeh @sdelamo Thank you for your advice!

I think an approach that works for me is to implement a DAO method for revoking tokens as in the guide, and then additionally listen for `LogoutEvent` to revoke the token in that case too. I think this combined with a task that periodically clears expired & revoked tokens will work well.
