### ISSUE TITLE
Token Refresh Cookie max-age should be configurable

### ISSUE THREAD

**Issue by sdelamo** [micronaut-projects/micronaut-security#333]
@istvanszoboszlai 

> JWT_REFRESH_TOKEN cookie max-age should be configurable (default value should be a lot longer than that of JWT, although I am not totally familiar with industry standard refresh token age suggestions.)

This is a subtask of: 

https://github.com/micronaut-projects/micronaut-security/issues/315

**Comment by sdelamo** [comment]
I think we should probably add to [RefreshTokenConfiguration](https://github.com/micronaut-projects/micronaut-security/blob/master/security-jwt/src/main/java/io/micronaut/security/token/jwt/generator/RefreshTokenConfiguration.java) a method     
`@NonNull Duration getCookieMaxAge()`. 

Then, we will need to inject `RefreshTokenConfiguration` to `JwtCookieLoginHandler`

**Comment by mphouston** [comment]
I think this is an important task.  The refresh token cookie expires at the same time as the access token.  Not super critical, but that defeats the purpose of the refresh token cookie (I think).  

I have had to work around this by using a _@replaces()_ subclass for JwtCookieLoginHandler.  

BTW, I do appreciate the core security work.  Along with -data, it helps me avoid a lot of work :).
