### ISSUE TITLE
Recognise absolute oauth2 callback-uri as absolute and don't append it to the base uri

### ISSUE THREAD

**Issue by brent777** [micronaut-projects/micronaut-security#370]
Would it be possible for the callback-uri to be recognised as absolute if it begins with http / https? Right now, it is considered relative no matter what, it seems.

I need to do this to try workaround a very strange issue that I experience with my Micronaut app in some environments (but not all) where it is trying to make the callback over http instead of https (no idea why since my application endpoints are available over https only). My hope is if this URI could be configured as absolute, then I could explicitly put "https" in the URI and work around this strange issue.
 
### Steps to Reproduce

1. Configure the oauth2 callback-uri in a yml like:

```callback-uri: https://xxxx/oauth/callback/azure```

2. Run the application and try authenticate.

3. Notice that the callback URI sent to the auth provider appends this value to the base URI, i.e. https://xxxx/https://xxxx/oauth/callback/azure causing auth to fail.

### Expected Behaviour

If I configure the callback-uri as https://xxxx/oauth/callback/azure, then I would expect it to be sent to the provider as https://xxxx/oauth/callback/azure and not  https://xxxx/https://xxxx/oauth/callback/azure.

### Actual Behaviour

It is sent to the provider as  https://xxxx/https://xxxx/oauth/callback/azure.

### Environment Information

- **Operating System**: Ubuntu
- **Micronaut Version:** 2.0.1
- **Kotlin Version:** 1.3.72

### Example Application

- Unfortunately the application is proprietary and in a private repository so I cannot provide this.

**Comment by jameskleeh** [comment]
@brent777 What is the use case for providing the full URL there? The host resolver should resolve the current server URL

**Comment by nikomakela** [comment]
It seems like this feature does not work anymore.

**Comment by jameskleeh** [comment]
@nikomakela As you can see in the commit we have a test for this case. If there is a problem please file a new issue with an example app to reproduce

**Comment by jjchiw** [comment]
Hi!

Did this change was merged?

I see the change in the commit

https://github.com/micronaut-projects/micronaut-security/blob/e94a521da1e93f2af5f5112bdc2a41c5b521697f/security-oauth2/src/main/java/io/micronaut/security/oauth2/url/DefaultOauthRouteUrlBuilder.java#L114

But it doesn't appear in the tag `2.0.1`

https://github.com/micronaut-projects/micronaut-security/blob/v2.0.1/security-oauth2/src/main/java/io/micronaut/security/oauth2/url/DefaultOauthRouteUrlBuilder.java#L114

So in the latest `2.4.2` tag 

https://github.com/micronaut-projects/micronaut-security/blob/v2.4.2/security-oauth2/src/main/java/io/micronaut/security/oauth2/url/DefaultOauthRouteUrlBuilder.java#L114

So, are you going to merge this or should I implement `OauthRouteUrlBuilder`

Thanks :)

**Comment by jameskleeh** [comment]
@jjchiw It appears I failed to create a PR for the branch. I just did https://github.com/micronaut-projects/micronaut-security/pull/643
