### ISSUE TITLE
Multiple Login Handler

### ISSUE THREAD

**Issue by alphawolf1988** [micronaut-projects/micronaut-security#374]
It would be really nice, if we could enable multiple login handlers at the same time, because it seems to be that the configuration:

`micronaut.security.authentication: ....`

only supports one configuration. As a scenario, i want to enable the login handler for IdToken in order to use Goolge, facebook, etc. OAuth 2.0 and i also want to enable the login handler for cookie jwt for my own email / password login. 

Is there something like a workaround in order to quick fix it for the current version?

**Comment by jameskleeh** [comment]
@alphawolf1988 You realize that will lead to the application handling multiple different types of jwt tokens? Ones from your oauth providers and ones for your own login? You can simply set `micronaut.security.authentication: cookie` and then you can normalize the tokens so you can rely on a consistent format.

I don't know how we could support multiple values there? How could we choose what to do after someone logs in?

**Comment by alphawolf1988** [comment]
@jameskleeh Of course, the applications needs to handle different jwt token types, but i mean the use case of having multiple login realms like google, facebook, email etc. is some common user experience. In the end micronaut needs to create a principal from a capable login facade and all following processes should work as expected. Micronaut could decide the login realm for example by cookie / header name and different endpoints for login. I could use Keycloak in order to support multiple login realms, but since micronaut supports them all out of the box. this makes no sense.

**Comment by jameskleeh** [comment]
> Of course, the applications needs to handle different jwt token types

It doesn't have to. Like I said above you can normalize all authentication sources into a common token format and have all tokens generated from Micronaut.

**Comment by alphawolf1988** [comment]
@jameskleeh Is there any good starting point / example in order to do this?

**Comment by jameskleeh** [comment]
@alphawolf1988 It works that way by default with `micronaut.security.authentication: cookie`

**Comment by jameskleeh** [comment]
The `OpenIdUserDetailsMapper` is responsible for converting the Oauth provider JWT claims into the UserDetails, which would be the common format

**Comment by alphawolf1988** [comment]
@jameskleeh thanks, i'll look into it. Feel free to close this ticket.
