### ISSUE TITLE
NullPointerException in IpPatternsRules

### ISSUE THREAD

**Issue by makubit** [micronaut-projects/micronaut-security#378]
We're facing issues when testing our service (especially during load tests) and getting NullPointerException on IpPatternsRules.

micronaut: 1.3.2

`
4","level":"ERROR","level_value":40000,"stack_trace":"java.lang.NullPointerException: null\n\tat io.micronaut.security.rules.IpPatternsRule.check(IpPatternsRule.java:97)\n\tat io.micronaut.security.filters.SecurityFilter.checkRules(SecurityFilter.java:147)\n\tat io.micronaut.security.filters.SecurityFilter.lambda$doFilterOnce$4(SecurityFilter.java:126)\n\tat io.micronaut.security.filters.SecurityFilter$$Lambda$1123.000000003C0434F0.call(Unknown Source)\n\tat io.reactivex.internal.operators.flowable.FlowableDefer.subscribeActual(FlowableDefer.java:35)\n\tat io.reactivex.Flowable.subscribe(Flowable.java:14918)\n\tat io.reactivex.Flowable.subscribe(Flowable.java:14865)\n\tat io.micronaut.reactive.rxjava2.RxInstrumentedFlowable.subscribeActual(RxInstrumentedFlowable.java:58)\n\tat io.reactivex.Flowable.subscribe(Flowable.java:14918)\n\tat io.reactivex.Flowable.subscribe(Flowable.java:14865)\n\tat io.reactivex.internal.operators.flowable.FlowableSwitchIfEmpty$SwitchIfEmptySubscriber.onComplete(FlowableSwitchIfEmpty.java:71)\n\tat io.micronaut.reactive.rxjava2.RxInstrumentedSubscriber.onComplete(RxInstrumentedSubscriber.java:101)\n\tat io.reactivex.internal.operators.flowable.FlowableFlatMap$MergeSubscriber.drainLoop(FlowableFlatMap.java:426)\n\tat io.reactivex.internal.operators.flowable.FlowableFlatMap$MergeSubscriber.drain(FlowableFlatMap.java:366)\n\tat io.reactivex.internal.operators.flowable.FlowableFlatMap$MergeSubscriber.onComplete(FlowableFlatMap.java:338)\n\tat io.micronaut.reactive.rxjava2.RxInstrumentedSubscriber.onComplete(RxInstrumentedSubscriber.java:101)\n\tat io.reactivex.internal.operators.maybe.MaybeToFlowable$MaybeToFlowableSubscriber.onComplete(MaybeToFlowable.java:80)\n\tat io.micronaut.reactive.rxjava2.RxInstrumentedMaybeObserver.onComplete(RxInstrumentedMaybeObserver.java:100)\n\tat io.reactivex.internal.operators.maybe.MaybeDoOnEvent$DoOnEventMaybeObserver.onComplete(MaybeDoOnEvent.java:115)\n\tat io.micronaut.reactive.rxjava2.RxInstrumentedMaybeObserver.onComplete(RxInstrumentedMaybeObserver.java:100)\n\tat io.reactivex.internal.operators.flowable.FlowableElementAtMaybe$ElementAtSubscriber.onComplete(FlowableElementAtMaybe.java:102)\n\tat io.micronaut.reactive.rxjava2.RxInstrumentedSubscriber.onComplete(RxInstrumentedSubscriber.java:101)\n\tat io.reactivex.internal.operators.flowable.FlowableFlatMap$MergeSubscriber.drainLoop(FlowableFlatMap.java:426)\n\tat io.reactivex.internal.operators.flowable.FlowableFlatMap$MergeSubscriber.drain(FlowableFlatMap.java:366)\n\tat io.reactivex.internal.operators.flowable.FlowableFlatMap$MergeSubscriber.onComplete(FlowableFlatMap.java:338)\n\tat io.micronaut.reactive.rxjava2.RxInstrumentedSubscriber.onComplete(RxInstrumentedSubscriber.java:101)\n\tat io.reactivex.internal.operators.flowable.FlowableFromIterable$IteratorSubscription.slowPath(FlowableFromIterable.java:255)\n\tat io.reactivex.internal.operators.flowable.FlowableFromIterable$BaseRangeSubscription.request(FlowableFromIterable.java:124)\n\tat io.reactivex.internal.operators.flowable.FlowableFlatMap$MergeSubscriber.onSubscribe(FlowableFlatMap.java:117)\n\tat io.micronaut.reactive.rxjava2.RxInstrumentedSubscriber.onSubscribe(RxInstrumentedSubscriber.java:55)\n\tat io.reactivex.internal.operators.flowable.FlowableFromIterable.subscribe(FlowableFromIterable.java:69)\n\tat io.reactivex.internal.operators.flowable.FlowableFromIterable.subscribeActual(FlowableFromIterable.java:47)\n\tat io.reactivex.Flowable.subscribe(Flowable.java:14918)\n\tat io.reactivex.Flowable.subscribe(Flowable.java:14865)\n\tat io.micronaut.reactive.rxjava2.RxInstrumentedFlowable.subscribeActual(RxInstrumentedFlowable.java:58)\n\tat io.reactivex.Flowable.subscribe(Flowable.java:14918)\n\tat io.reactivex.internal.operators.flowable.FlowableFlatMap.subscribeActual(FlowableFlatMap.java:53)\n\tat io.reactivex.Flowable.subscribe(Flowable.java:14918)\n\tat io.reactivex.Flowable.subscribe(Flowable.java:14865)\n\tat io.micronaut.reactive.rxjava2.RxInstrumentedFlowable.subscribeActual(RxInstrumentedFlowable.java:58)\n\tat io.reactivex.Flowable.subscribe(Flowable.java:14918)\n\tat io.reactivex.internal.operators.flowable.FlowableElementAtMaybe.subscribeActual(FlowableElementAtMaybe.java:36)\n\tat io.reactivex.Maybe.subscribe(Maybe.java:4290)\n\tat io.micronaut.reactive.rxjava2.RxInstrumentedMaybe.subscribeActual(RxInstrumentedMaybe.java:53)\n\tat io.reactivex.Maybe.subscribe(Maybe.java:4290)\n\tat io.reactivex.internal.operators.maybe.MaybeDoOnEvent.subscribeActual(MaybeDoOnEvent.java:39)\n\tat io.reactivex.Maybe.subscribe(Maybe.java:4290)\n\tat io.micronaut.reactive.rxjava2.RxInstrumentedMaybe.subscribeActual(RxInstrumentedMaybe.java:53)\n\tat io.reactivex.Maybe.subscribe(Maybe.java:4290)\n\tat io.reactivex.internal.operators.maybe.MaybeToFlowable.subscribeActual(MaybeToFlowable.java:45)\n\tat io.reactivex.Flowable.subscribe(Flowable.java:14918)\n\tat io.reactivex.Flowable.subscribe(Flowable.java:14865)\n\tat io.micronaut.reactive.rxjava2.RxInstrumentedFlowable.subscribeActual(RxInstrumentedFlowable.java:58)\n\tat io.reactivex.Flowable.subscribe(Flowable.java:14918)\n\tat io.reactivex.internal.operators.flowable.FlowableFlatMap.subscribeActual(FlowableFlatMap.java:53)\n\tat io.reactivex.Flowable.subscribe(Flowable.java:14918)\n\tat io.reactivex.Flowable.subscribe(Flowable.java:14865)\n\tat io.micronaut.reactive.rxjava2.RxInstrumentedFlowable.subscribeActual(RxInstrumentedFlowable.java:58)\n\tat io.reactivex.Flowable.subscribe(Flowable.java:14918)\n\tat io.reactivex.internal.operators.flowable.FlowableSwitchIfEmpty.subscribeActual(FlowableSwitchIfEmpty.java:32)\n\tat io.reactivex.Flowable.subscribe(Flowable.java:14918)\n\tat io.reactivex.Flowable.subscribe(Flowable.java:14865)\n\tat io.micronaut.reactive.rxjava2.RxInstrumentedFlowable.subscribeActual(RxInstrumentedFlowable.java:58)\n\tat io.reactivex.Flowable.subscribe(Flowable.java:14918)\n\tat io.reactivex.Flowable.subscribe(Flowable.java:14868)\n\tat io.micronaut.http.context.ServerRequestTracingPublisher.lambda$subscribe$0(ServerRequestTracingPublisher.java:52)\n\tat io.micronaut.http.context.ServerRequestTracingPublisher$$Lambda$1129.000000003C045F10.run(Unknown Source)\n\tat io.micronaut.http.context.ServerRequestContext.with(ServerRequestContext.java:68)\n\tat io.micronaut.http.context.ServerRequestTracingPublisher.subscribe(ServerRequestTracingPublisher.java:52)\n\tat io.micronaut.configuration.metrics.binder.web.WebMetricsPublisher.subscribe(WebMetricsPublisher.java:153)\n\tat io.reactivex.internal.operators.flowable.FlowableFromPublisher.subscribeActual(FlowableFromPublisher.java:29)\n\tat io.reactivex.Flowable.subscribe(Flowable.java:14918)\n\tat io.reactivex.Flowable.subscribe(Flowable.java:14865)\n\tat io.reactivex.internal.operators.flowable.FlowableSubscribeOn$SubscribeOnSubscriber.run(FlowableSubscribeOn.java:82)\n\tat
`

I see that similar issue has been reported here: https://github.com/micronaut-projects/micronaut-security/issues/186 and it should be resolved in version 1.3.2.
We still have this problem, what causes multiple errors.

**Comment by graemerocher** [comment]
Please provide an example with steps to reproduce

**Comment by makubit** [comment]
I don't think it can be reproducible with simple application (I will try to create one and reproduce the issue).
Anything else that I can provide you?

We don't use setting `ip-patterns` in application configuration, but adding 
```
  security:
    ip-patterns: []
``` 
seems to help with this error. I see it can be a workaround, not solution for this issue.

**Comment by jameskleeh** [comment]
> I see that similar issue has been reported here: #186 and it should be resolved in version 1.3.2.

It is included in 1.3.2 of Micronaut Security, which was not included by default in Micronaut until 1.3.4. Please test this works with at least that Micronaut version
