### ISSUE TITLE
micronaut-bom 2.0.1 (in micronaut-security) requires a non-existent version of ktor-bom (1.3.2)

### ISSUE THREAD

**Issue by Archcry** [micronaut-projects/micronaut-security#422]
### Task List

- [x] Steps to reproduce provided
- [x] Stacktrace (if present) provided
- [x] Example that reproduces the problem uploaded to Github
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

1. Clone https://github.com/Archcry/micronaut-security-bom-bug-reproduction.git
2. Run `mvn clean compile`
3. Observe the error

### Expected Behaviour

When using the `micronaut bom` (instead of the `micronaut-parent`) and maven central rather than jcentral it should be able to download a version of `ktor-bom`.

### Actual Behaviour

```
Failed to execute goal on project ktor-bug: Could not resolve dependencies for project example.micronaut:ktor-bug:jar:0.1: Failed to collect dependencies at io.micronaut.security:micronaut-security-jwt:jar:2.1.1: Failed to read Failure to find io.ktor:ktor-bom:pom:1.3.2 in https://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced
```

When using Maven Central repository in combination with `micronaut-bom` and `micronaut-security` it tries to download version `1.3.2` of `ktor-bom` which does not exist on maven central. The version of `ktor-bom` in `micronaut-bom` is correct (`1.4.0`) but the version of `ktor-bom` in `micronaut-security` dependency management section is causing problems because it is version `1.3.2`.

Most likely same problem as https://github.com/micronaut-projects/micronaut-core/issues/3933

### Environment Information

- **Operating System**: ArchLinux
- **Micronaut Version:** 2.1.2 (and `micronaut-security:2.1.1`)
- **JDK Version:** OpenJDK 11.0.8 2020-07-14

### Example Application

- https://github.com/Archcry/micronaut-security-bom-bug-reproduction.git

**Comment by dreaneii** [comment]
We're also experiencing this problem.
We see that version `2.1.2` of `micronaut-security` (released on 27 October) is still using version `2.0.1` of the `micronaut-bom`

**Comment by drvdijk** [comment]
Also see:

- https://github.com/ktorio/ktor/issues/1942
- https://youtrack.jetbrains.com/issue/KTOR-342

It seems micronaut 2.1.3 is using ktor version 1.4.0 which is in maven central. However the 2.1.3 bom specifies dependencies that in turn again use the 2.0.1 version of the bom (eg micronaut-openapi is at 2.1.1 that again uses 2.0.1 of the micronaut bom).

**Comment by graemerocher** [comment]
All modules need to be upgraded to Micronaut 2.1.3 and not use 2.0.x.

In the meantime the workaround is to add `jcenter()` to your repositories in Gradle

**Comment by drvdijk** [comment]
@graemerocher we're still using Maven, adding jcenter is quite a hassle with creating custom images with custom settings.xml files in our build pipelines. Not quite worth it I guess when new Micronaut module versions might be available soon

**Comment by alvarosanchez** [comment]
@drvdijk can you not simply add JCenter as a `<repository>` in your POM?

**Comment by sdelamo** [comment]
I am going to try to release new versions of micronaut security 2.1.x and 2.2.x

**Comment by sdelamo** [comment]
I've released Micronaut security 2.1.3

I think you error will be gone if you replace your security dependencies with:

```xml
<dependency>
  <groupId>io.micronaut.security</groupId>
  <artifactId>micronaut-security-annotations</artifactId>
  <version>2.1.3</version>
  <exclusions>
    <exclusion>
      <groupId>io.micronaut.security</groupId>
      <artifactId>*</artifactId>
    </exclusion>
  </exclusions>
</dependency>
<dependency>
  <groupId>io.micronaut.security</groupId>
  <artifactId>micronaut-security</artifactId>
  <version>2.1.3</version>
  <exclusions>
    <exclusion>
      <groupId>io.micronaut.security</groupId>
      <artifactId>*</artifactId>
    </exclusion>
  </exclusions>
</dependency>
<dependency>
    <groupId>io.micronaut.security</groupId>
    <artifactId>micronaut-security-jwt</artifactId>
    <version>2.1.3</version>
  <exclusions>
    <exclusion>
      <groupId>io.micronaut.security</groupId>
      <artifactId>*</artifactId>
    </exclusion>
  </exclusions>
</dependency>
```

**Comment by Archcry** [comment]
That's awesome, thanks!

**Comment by drvdijk** [comment]
@alvarosanchez yes right, I wasn't thinking straight there 😊 We'll dig into seeing if that's a good temporary solution.

@sdelamo thanks for the release!

Next step I suppose is waiting for other modules to upgrade as well, and then to wait for the micronaut bill of materials to be updated to point to all these new module versions, right?
