### ISSUE TITLE
Oauth redirect without https in elastic beanstalk

### ISSUE THREAD

**Issue by dllewellyn** [micronaut-projects/micronaut-security#480]
I am having an issue with auth when hosting an app in elastic beanstalk. The configuration is setup so that the elastic beanstalk load balancer handles the SSL connection. When I go to /oauth/login/<provider> it redirects me correctly to the auth provider's login page, but with the redirect_uri set as http rather than https

### Steps to Reproduce

1. Run app in elasticbeanstalk
2. Configure app with load balancer / ssl 
3. Navigate to https://<url>/oauth/login/<provider>
4. Observe the redirect_uri does not include https

### Expected Behaviour

The redirect should happen with the https in it

**Comment by sdelamo** [comment]
It is not an issue of the security module.  You have to configure Micronaut's [HTTP Host Resolution](https://docs.micronaut.io/latest/guide/index.html#hostResolution)

You will need to configure it to use X-Forwarded headers used by AWS: 

https://docs.aws.amazon.com/elasticloadbalancing/latest/classic/x-forwarded-headers.html


Probably something close to: 

```yaml
---
micronaut:
  server:
    host-resolution:
      protocol-header: X-Forwarded-Proto
      port-header: X-Forwarded-Port
      host-header: Host
```

You can troubleshoot how your host is being resolved with such a sample controller: 

```java
package uk.co.metadataworks.auth.controllers;

import io.micronaut.http.HttpRequest;
import io.micronaut.http.MediaType;
import io.micronaut.http.annotation.Controller;
import io.micronaut.http.annotation.Get;
import io.micronaut.http.annotation.Produces;
import io.micronaut.http.server.util.HttpHostResolver;
import io.micronaut.security.annotation.Secured;
import io.micronaut.security.rules.SecurityRule;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

@Controller("/host")
public class HostController {
    private static final Logger LOG = LoggerFactory.getLogger(HostController.class);

    private final HttpHostResolver httpHostResolver;

    public HostController(HttpHostResolver httpHostResolver) {
        this.httpHostResolver = httpHostResolver;
    }

    @Produces(MediaType.TEXT_PLAIN)
    @Secured(SecurityRule.IS_ANONYMOUS)
    @Get
    public String host(HttpRequest<?> request) {
        for (String headerName : request.getHeaders().names()) {
            if (LOG.isInfoEnabled()) {
                LOG.info("H {}: {}", headerName, request.getHeaders().get(headerName));
            }
        }
        return httpHostResolver.resolve(request);
    }
}
```
