### ISSUE TITLE
Wrong micronaut-security-oauth2 and jwt reference?

### ISSUE THREAD

**Issue by rafaelrenanpacheco** [micronaut-projects/micronaut-security#486]
Hello!

When following the [OAuth 2 installation guide](https://micronaut-projects.github.io/micronaut-security/latest/guide/#installation) it tell us to import this:

```
implementation("io.micronaut:micronaut-security-oauth2")
implementation("io.micronaut:micronaut-security-jwt")
```

Which didn't work. What did work was this one:

```
implementation("io.micronaut.security:micronaut-security-oauth2")
implementation("io.micronaut.security:micronaut-security-jwt")
```

I tried to fix the docs but I didn't found where to change this dependency reference.

**Comment by sdelamo** [comment]
@rafaelrenanpacheco thanks for reporting the issue.
