### ISSUE TITLE
can't use oauth2 micronaut with snapshot reposistory

### ISSUE THREAD

**Issue by Malik33000** [micronaut-projects/micronaut-security#52]
I try to test oauth2 micronaut : 

But I can not include security-oauth2 by including in gradle dependencies :

   compile "io.micronaut.configuration:security-oauth2:1.2.0.BUILD-SNAPSHOT"

or 
compile "io.micronaut:security-oauth2:1.2.0.BUILD-SNAPSHOT"

with repository : 
repositories {
    maven { url "https://oss.sonatype.org/content/repositories/snapshots/" }
    maven { url "https://jcenter.bintray.com" }
    jcenter()
}

it's working with  

 annotationProcessor "io.micronaut:micronaut-security:1.2.0.BUILD-SNAPSHOT"
 compile "io.micronaut:micronaut-security:1.2.0.BUILD-SNAPSHOT"

but not for oauth2... how can I do that ?

**Comment by jameskleeh** [comment]
Please ask questions in gitter. The artifact name is `io.micronaut.configuration:micronaut-security-oauth2`
