### ISSUE TITLE
Getting null HttpRequest object in custom GenericJwtClaimsValidator implementation

### ISSUE THREAD

**Issue by VinitTomar** [micronaut-projects/micronaut-security#526]
- [x] Steps to reproduce provided
- [x] Example that reproduces the problem uploaded to Github
- [x] Full description of the issue provided

### Steps to Reproduce

1. Run cmd `./gradlew -t run`  

2. Get jwt token with below curl 
```curl --location --request POST 'localhost:8080/login' \
--header 'Content-Type: application/json' \
--data-raw ' {
     "username":"vinit",
     "password":"tomar"
 }'
```
3. Execute below curl for `secured` endpoint
```curl --location --request GET 'localhost:8080/secured' \
--header 'Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ2aW5pdCIsIm5iZiI6MTYwODg3MjI0NSwicm9sZXMiOltdLCJpc3MiOiJtaWNyb25hdXQtdHV0IiwiZXhwIjoxNjA4ODc1ODQ1LCJpYXQiOjE2MDg4NzIyNDV9.B-0D299Rv3Pm1V3jdJcExzRsr6VG2s38IF8mnC5S1eM'
``` 
4. See the console

### Expected Behaviour

validator with request => (HttpRequest Object reference)

### Actual Behaviour

validator with request => null

### Environment Information

- **Operating System**: Mac OS
- **Micronaut Version:** 2.2.1
- **JDK Version:** 15.0.1

### Example Application

- link to github repository [here](https://github.com/VinitTomar/micronaut-learn.git)
- File path with contain code [here](https://github.com/VinitTomar/micronaut-learn/blob/main/src/main/java/micronaut/tut/VinJwtClaimValidator.java)

**Comment by sdelamo** [comment]
To avoid introducing a breaking change we introduce several methods which allow you to supply the request through the validation chain. 

But the request will not be passed unless you provide a  replacement of `JwtTokenValidator::validateToken(String, HttpRequest)`

E.g.:

@Singleton
@Replaces(JwtTokenValidator.class)
public JwtTokenValidatorReplacement extends JwtTokenValidator {
@Override 
public Publisher<Authentication> validateToken(String token, HttpRequest<?> request) {
        return validator.validate(token, request)
                .flatMap(jwtAuthenticationFactory::createAuthentication)
                .map(Flowable::just)
                .orElse(Flowable.empty());
    }
}
```

The following method will be removed in the next release mayor release of Micronaut Security

`JwtClaimsValidator::validate(JwtClaims) `
`TokenValidator::validate(String)`
`JwtValidator::validate(String)`
