### ISSUE TITLE
ClientCredentialsClient not injected in BeanContext

### ISSUE THREAD

**Issue by sdhimmar006** [micronaut-projects/micronaut-security#541]
I am trying to use client credentials in micronaut as specified by https://micronaut-projects.github.io/micronaut-security/latest/guide/#clientcredentials

1. In application.yml put following configuration 

2. Put the below line in a function that gets called by controller method. 

ClientCredentialsClient client=beanContext.getBean(ClientCredentialsClient.class, Qualifiers.byName("companyauthserver"));
where i have beanContext is of class BeanContext and it is injected by @Inject.

### Expected Behaviour
1. Server should start 
2. It should run fine and beanContext should provide ClientCredentialsClient class.

### Actual Behaviour

An error comes saying that ClientCredentialsClient does not exist. 

### Environment Information

- **Operating System**: Windows 7
- **Micronaut Version:** 2.1.2
- **JDK Version:** GraalVM 20.3.0

**Comment by sdelamo** [comment]
> 1. In application.yml put following configuration 

What configuration?

**Comment by sdhimmar006** [comment]
Able to do it now. Upgraded to micronaut-parent 2.x + and it worked. Closing the issue
