### ISSUE TITLE
security-ldap uses old package

### ISSUE THREAD

**Issue by ilopmar** [micronaut-projects/micronaut-security#558]
The module `security-ldap` is still using the old `io.micronaut.configuration.security.ldap` package instead of the new `io.micronaut.security.ldap`. The rest of the modules are using correctly an `io.micronaut.security.xxxx` package.

**Comment by sdelamo** [comment]
I think we should change it in Micronaut security 3.0 

The maven group is correct: 

https://mvnrepository.com/artifact/io.micronaut.security/micronaut-security-ldap

**Comment by ilopmar** [comment]
Yes, make sense to wait until next major version
