### ISSUE TITLE
Support access to request during authentication

### ISSUE THREAD

**Issue by jameskleeh** [micronaut-projects/micronaut-security#57]

**Comment by cristianrgreco** [comment]
I've run into this today. We authenticate with a third party and need to propagate a request header via the @Client interface. Based on the current API there is no way to access the request header during the authentication flow.

**Comment by cristianrgreco** [comment]
Hi @jameskleeh , why has this been closed?

**Comment by jameskleeh** [comment]
Because it’s finished

**Comment by cristianrgreco** [comment]
Where can I find the code/docs? There are no associated comments/PRs

**Comment by jameskleeh** [comment]
In the master branch

**Comment by cristianrgreco** [comment]
Hi @jameskleeh 

Am I right in saying this change has been reverted? https://github.com/micronaut-projects/micronaut-security/commit/7f638aa1905e5ba88601b39c79277cb21aca5a8c

**Comment by jameskleeh** [comment]
@cristianrgreco No. The request was added then removed from token validators. Still there for authentication providers

**Comment by cristianrgreco** [comment]
@jameskleeh Thanks. Just to confirm, this isn't available in 1.3.x right?

**Comment by jameskleeh** [comment]
@cristianrgreco Correct

**Comment by jameskleeh** [comment]
@cristianrgreco I'm considering releasing a 1.4 to better prepare folks for these changes. It may include this change as an additional method. Not sure though

**Comment by jameskleeh** [comment]
A new default method that takes the request was added

**Comment by cristianrgreco** [comment]
For anyone else interested the change is here: https://github.com/micronaut-projects/micronaut-security/blob/1.4.x/security/src/main/java/io/micronaut/security/authentication/AuthenticationProvider.java#L49

@jameskleeh Any idea on when a 1.4.x release might happen?

**Comment by jameskleeh** [comment]
Hoping to do an RC soon
