### ISSUE TITLE
Unnecessary invocation

### ISSUE THREAD

**Issue by fivig** [micronaut-projects/micronaut-security#574]
Please move 
`Map<String, Object> attributes = authentication.getAttributes();`
to the log condition othewise attributes never used. Should be:
`
                    if (LOG.isDebugEnabled()) {
 Map<String, Object> attributes = authentication.getAttributes();
                        LOG.debug("Attributes: {}", attributes
                                .entrySet()
                                .stream()
                                .map((entry) -> entry.getKey() + "=>" + entry.getValue().toString())
                                .collect(Collectors.joining(", ")));
                    }`

**Comment by graemerocher** [comment]
Sounds like a great opportunity to send a PR 😉
