### ISSUE TITLE
Limit access to service based on IP only

### ISSUE THREAD

**Issue by shkdmhhb** [micronaut-projects/micronaut-security#59]
Is it possible to setup access to service based on IP only (using ip-patterns), without setting up any security providers?

Given the tests below, if it passes the ip-patterns, it is still failing with `No rule provider authorized or rejected the request.`

If it fails the ip-patterns, you get `The rule provider io.micronaut.security.rules.IpPatternsRule rejected the request.`

So based on the tests below, i know the ip-pattern rule is working.  Are there any other configurations needed to just protect the endpoint based the the client IP?

Looking at the [IpPattern code](https://github.com/micronaut-projects/micronaut-security/blob/master/security/src/main/java/io/micronaut/security/rules/IpPatternsRule.java), when it passes the ip-pattern rule, it seem to always to return `SecurityRuleResult.UNKNOWN`

```java
    public SecurityRuleResult check(HttpRequest request, @Nullable RouteMatch routeMatch, @Nullable Map<String, Object> claims) {

        if (patternList.isEmpty()) {
            return SecurityRuleResult.UNKNOWN;
        } else {
            if (patternList.stream().anyMatch(pattern ->
                    pattern.pattern().equals(SecurityConfigurationProperties.ANYWHERE) ||
                    pattern.matcher(request.getRemoteAddress().getAddress().getHostAddress()).matches())) {
                return SecurityRuleResult.UNKNOWN;
            } else {
                return SecurityRuleResult.REJECTED;
            }
        }
    }
```

## Test 1:
Secenario:  Testing from 127.0.0.1, results in log entries below.

```yml
micronaut:
  application:
    name: test-app
  security:
    enabled: true
    ip-patterns:
      - '127.0.0.1'
```

15:41:37.320 [pool-1-thread-7] DEBUG i.m.security.filters.SecurityFilter - Failure to authenticate request. GET /test.
15:41:37.324 [pool-1-thread-7] DEBUG i.m.security.filters.SecurityFilter - Authorized request GET /test. No rule provider authorized or rejected the request.

## Test 2:
Secenario:  Testing from 127.0.0.1, results in log entries below.

```yml
micronaut:
  application:
    name: test-app
  security:
    enabled: true
    ip-patterns:
      - '198.1.1.1'
```
15:46:58.376 [pool-1-thread-4] DEBUG i.m.security.filters.SecurityFilter - Failure to authenticate request. GET /test.
15:46:58.381 [pool-1-thread-4] DEBUG i.m.security.filters.SecurityFilter - Unauthorized request GET /test. The rule provider io.micronaut.security.rules.IpPatternsRule rejected the request.

**Comment by jameskleeh** [comment]
Yeah currently the IP patterns aren't designed to specifically authorize requests, but only reject requests if the IP doesn't match. You could provide your own `SecurityRule` that runs after the ip rule (IpPatternsRule.ORDER + 1) that always returns `ALLOWED`.

**Comment by jameskleeh** [comment]
I think this is an uncommon enough use case that adding explicit support for it is probably not worth it, especially given that a relatively easy way to get the desired behavior is available.
