### ISSUE TITLE
Allow 404 global error to be displayed even with a security enabled

### ISSUE THREAD

**Issue by tchiotludo** [micronaut-projects/micronaut-security#6]
### Steps to Reproduce

1. Add a global 404 error `@Error(status = HttpStatus.NOT_FOUND, global = true)`
2. Enable security with `micronaut.security.enabled: true`
3. Add a controller with parameter like 
```java
@Secured(Role.ROLE_CONNECT_READ)
@Controller("/{cluster}/connect")
public class ConnectController {
```
4. Try to reach every child page like `/test/connect/bla`
5. be redirected to unauthorized url 
6. Disabled security with `micronaut.security.enabled: false`
7. Try to reach the same page like `/test/connect/bla`
8. see the 404 page

### Expected Behaviour

Security should not change the behavior off 404 page and must be check before security for some use case.
The best will be to let user have an option to allow choose if you you want to have a 404 or a unauthorized response.

I think the better option is to allow 404 before unauthorized if the ErrorController is annotated with : `@Secured(SecurityRule.IS_ANONYMOUS)`
 
### Environment Information

- **Operating System**: [Docker alpine](https://github.com/tchiotludo/kafkahq/blob/dev/Dockerfile)
- **Micronaut Version:** 1.1.0
- **JDK Version:** openjdk:8-jre-alpine

### Example Application

Full source code is [here](https://github.com/tchiotludo/kafkahq) on branch `dev`

**Comment by jlannoy** [comment]
I'm facing this issue. When you said "If a request comes through and **no** security rule explicitly rejects or allows it, it is rejected by default.", I completely agree. It should be the default way of handling. But adding a @Secured(SecurityRule.IS_ANONYMOUS) on one @Error management controller method should not have no effect... As we did explicitly write a well formed security rule. 

Maybe it could in fact be a bug? I didn't find yet why but in fact on a 404 not found, when declaring a corresponding @Error, a route match is identified to the error controller but not given to the SecurityFilter (null). So probably not set in the request attributes. The SecuredAnnotationRule always return a unknown result if the route match is undefined (around line 75).

I even tried implementing my own SecurityRule. Check this extract of a debug log : 

> RoutingInBoundHandler - Matching route GET - /secured/notExistPage
> RoutingInBoundHandler - No matching route found for URI /secured/notExistPage and method GET
> RoutingInBoundHandler - Matched route GET - /secured/notExistPage to controller class mn.test.controllers.GlobalErrorHandlers
> AnonymousAccessRule - request = /secured/notExistPage
> AnonymousAccessRule - route match = null

While on an existing route we would have : 

> RoutingInBoundHandler - Matched route GET - /secured/hello to controller class mn.test.controllers.SecuredController
> AnonymousAccessRule - request = /secured/hello
> AnonymousAccessRule - route match = class io.micronaut.web.router.DefaultUriRouteMatch

**Comment by tchiotludo** [comment]
🆙

**Comment by jameskleeh** [comment]
@jlannoy 

>  But adding a @secured(SecurityRule.IS_ANONYMOUS) on one @error management controller method should not have no effect... As we did explicitly write a well formed security rule.

The security filter doesn't handle anything with an error route. At that point the user was already validated at the entry point of the system.

```
@Secured("ROLE_ADMIN")
@Controller
class MyCtrl {

    @Get
    String someMethod() {
        throw new SomeException()
    }

}
```

If you have an exception route for `SomeException`, adding security logic to that doesn't make any sense because the validation only occurs at the entry point.

**Comment by jlannoy** [comment]
As it concerns 404 not found errors, In this case, no validation occurred... But even, that was not the real point, only one supposition. The real problem to fix was that it was not possible to get a 404 error page on a secured app.

**Comment by jameskleeh** [comment]
That isn’t true. Authenticated requests to a resource that the user has
access to but does not exist would result in a 404.

**Comment by tchiotludo** [comment]
:cry:

**Comment by jameskleeh** [comment]
@tchiotludo Do you realize the milestone set on this issue means it is set to be released for that version? It being closed means its finished.

**Comment by tchiotludo** [comment]
sorry @jameskleeh didn't notice. 
Most of the time, we link a commit or a PR for any issue, and don't see it this time :) 

Sorry and thanks for that :+1:

**Comment by jameskleeh** [comment]
https://github.com/micronaut-projects/micronaut-security/commit/bab9de3c7e60aef98e8cef5c4ab258498bc3e00d

**Comment by tchiotludo** [comment]
nice work, just a boolean to configure it 
thanks :smile:

**Comment by jlannoy** [comment]
And for the record, it fixes what I was describing too.
