### ISSUE TITLE
Application times out when combining oauth2 with @Client

### ISSUE THREAD

**Issue by fireXtract** [micronaut-projects/micronaut-security#602]
### Task List

- [x] Steps to reproduce provided
- [ ] Stacktrace (if present) provided
- [x] Example that reproduces the problem uploaded to Github
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

1. Launch with IntelliJ or whateva
2. Setup keycloak ala readme in example application
2. GET /test as an entry point
3. View HttpClient trace logs on running application and notice a successful token response
3. Application hangs indefinitely

### Expected Behaviour

The HttpRequest made by the @Client should connect to the goog url with bearer token in headers.

### Actual Behaviour

The bearer token is received by the app, but the chain of calls hangs, and no call to google is ever made.

### Environment Information

- **Operating System**: Ubuntu 18 LTS
- **Micronaut Version:** 2.4.1
- **JDK Version:** 11 coretta

### Example Application

https://github.com/fireXtract/micronaut-blocking-issue

**Comment by sdelamo** [comment]
hi @fireXtract I don't think it is a security issue. Your sample app does not work without security module. 

is this controller supposed to return the HTML page when you visit https://google.com?

```
package com.example;

import io.micronaut.http.MediaType;
import io.micronaut.http.annotation.Controller;
import io.micronaut.http.annotation.Get;
import io.micronaut.security.annotation.Secured;
import io.micronaut.security.rules.SecurityRule;

import javax.inject.Inject;

@Controller("/")
@Secured(SecurityRule.IS_ANONYMOUS)
public class TestController {
    @Inject
    private GoogleClient googleClient;

    @Get(uri="/test", produces = MediaType.APPLICATION_JSON_STREAM)
    public String greet(){
        System.out.println("got here");
        return String.join("", googleClient.getStrings().toList().blockingGet());
    }
}
```

Should not the media type be `MediaType.TEXT_PLAIN`. 

Also, `https://www.google.com` seems to be causing a 301 redirection to `https://www.google.com/` which I think causes a loop. 

I am going to close the issue. If you can create sample app which is runnable without the security module please attach it and reopen the issue.

**Comment by fireXtract** [comment]
The endpoint and body of greet are arbitrary, it never gets called when viewing the trace logs for HTTPClient. How are you seeing it 301?

**Comment by sdelamo** [comment]
I added logs

<logger name="io.micronaut.http.client" level="TRACE"/>

I will create a sample app with another url other than google.com

**Comment by fireXtract** [comment]
Strange. I look forward to your modified app to see if we've got more WOMM behavior.
https://github.com/fireXtract/micronaut-blocking-issue/blob/9edc0cd24dbd48cb8a91170889db16f4ca78e8ad/src/main/resources/logback.xml#L12

**Comment by sdelamo** [comment]
what does WOMM stand for?

**Comment by fireXtract** [comment]
Works on my machine :)
