### ISSUE TITLE
ErrorResponse::getError return string instead of enum

### ISSUE THREAD

**Issue by sdelamo** [micronaut-projects/micronaut-security#612]
To be more flexible and support providers which return error codes which are not defined in https://openid.net/specs/openid-connect-core-1_0.html#AuthError we could change:

```
public interface ErrorResponse  {

ErrorCode getError() 

...
}
```

to return  a String instead of an enum:

```
public class ErrorResponse  {

String getError() 

...
}```

This will be breaking change but I think we should do it in the next mayor version of Micronaut Security. 

this relates to https://github.com/micronaut-projects/micronaut-security/issues/605

**Comment by jeremyg484** [comment]
The handling of unexpected error codes has already been implemented in #1231.
