### ISSUE TITLE
DefaultAuthorizationExceptionHandler does not send "WWW-AUTHENTICATE" header

### ISSUE THREAD

**Issue by ratcashdev** [micronaut-projects/micronaut-security#648]
### Steps to Reproduce

1. Follow the guide for basic authentication here: https://guides.micronaut.io/latest/micronaut-security-basicauth-gradle-java.html
2. Stop after step 4.3.
3. Micronaut config:
```
micronaut:
  security:
    enabled: true
```
4. Call the resource from your browser

### Expected Behaviour

for HTTP 401 the browser should show a window asking for username and password
https://stackoverflow.com/questions/3297048/403-forbidden-vs-401-unauthorized-http-responses

### Actual Behaviour

HTTP 401 without asking for credentials

### Environment Information

- **Operating System**: Arch Linux
- **Micronaut Version:** 2.5.3
- **JDK Version:** 11

**Comment by sdelamo** [comment]
Hi, thanks for the feedback. 

I don't think we can create a generic solution since the value of `WWW-Authenticate` header will depend on the user application. However, you can create replace the default handler `DefaultAuthorizationExceptionHandler `for  `AuthorizationExceptionHandler` such as:  


```java
package example.micronaut;

import io.micronaut.context.annotation.Replaces;
import io.micronaut.http.HttpRequest;
import io.micronaut.http.HttpResponse;
import io.micronaut.http.HttpStatus;
import io.micronaut.http.MutableHttpResponse;
import io.micronaut.security.authentication.AuthorizationException;
import io.micronaut.security.authentication.DefaultAuthorizationExceptionHandler;

import javax.inject.Singleton;

@Singleton
@Replaces(DefaultAuthorizationExceptionHandler.class)
public class DefaultAuthorizationExceptionHandlerReplacement extends DefaultAuthorizationExceptionHandler {

    @Override
    protected MutableHttpResponse<?> httpResponseWithStatus(HttpRequest request, AuthorizationException exception) {
        if (exception.isForbidden()) {
            return HttpResponse.status(HttpStatus.FORBIDDEN);
        }
        return HttpResponse.status(HttpStatus.UNAUTHORIZED).header("WWW-Authenticate", "Basic realm=\"Micronaut Guide\"");
    }
}```

I will create a section in the guide to show this example.

**Comment by ratcashdev** [comment]
Understood.
While updating the doc, you could mention, that even though someone throws a `AuthenticationException` from his `AuthenticationProvider` (like below), he is still supposed to handle an `AuthorizationException`. Quite unintuitive and took me great deal of time to figure out why isn't it working.

```java
@Singleton
public class AuthenticationProviderUserPassword implements AuthenticationProvider {

    @Inject
    Users store;

    @Override
    public Publisher<AuthenticationResponse> authenticate(HttpRequest<?> httpRequest, AuthenticationRequest<?, ?> req) {
        String username = req.getIdentity().toString();
        String password = req.getSecret().toString();
        if (password.equals(store.getUserPassword(username))) {
            UserDetails details = new UserDetails(username, Collections.singletonList(store.getUserRole(username)));
            return Flowable.just(details);
        } else {
            return Flowable.create(emitter -> {
                emitter.onError(new AuthenticationException(new AuthenticationFailed()));
            }, BackpressureStrategy.ERROR);
        }
    }
```

**Comment by sdelamo** [comment]
>  he is still supposed to handle an AuthorizationException. Quite unintuitive and took me great deal of time to figure out why isn't it working.

He does not need to handle the exception. There is a `DefaultAuthorizationExceptionHandler`

**Comment by ratcashdev** [comment]
@sdelamo you're right. The point I was trying to make was that while i attempted to add the WWW-Authenticate header myself inside the `AuthenticationExceptionHandler`, it was not called and I had to debug the framework to realize that such a handler is not going to be called (ever?) and instead i have to implement an `AuthorizationExceptionHandler`.
In other words the unintuitive thing is, that i am explicitely throwing exception `X`, but I have to handle exception `Y`.
