### ISSUE TITLE
Request body is not present in `SecurityRule`

### ISSUE THREAD

**Issue by tcrespog** [micronaut-projects/micronaut-security#689]
### Task List

- [x] Steps to reproduce provided
- [x] Example that reproduces the problem uploaded to Github
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

1. Download the [example application](https://github.com/tcrespog/mn-security-rule-body).
2. Run the `PetControllerTest`, which performs a request to an endpoint secured with a `CustomSecurityRule`.
3. The `CustomSecurityRule` throws an exception because it expects the request body to be present (but it's not).

### Expected Behaviour

The request body should be populated by the time the security rule is processed.

### Actual Behaviour

The request body is not populated by the time the security rule is processed.

I have a custom [`SecurityRule`](https://github.com/micronaut-projects/micronaut-security/blob/master/security/src/main/java/io/micronaut/security/rules/SecurityRule.java) which reads data from the request body. However, when upgrading the app to Micronaut 2.5.6, I've realized that the body is not present in the `request` by the time the security rule is executed.
Apparently, this is happening since Micronaut 2.5.0.

### Environment Information

- **Micronaut Version:** 2.5.6
- **JDK Version:** 11

### Example Application

- https://github.com/tcrespog/mn-security-rule-body

**Comment by tcrespog** [comment]
I found this PR which explains the change of behavior: https://github.com/micronaut-projects/micronaut-core/pull/5261.

Now I understand that the absence of body in filters is intentional, therefore it won't be present in security rules as they are executed in the [`SecurityFilter`](https://github.com/micronaut-projects/micronaut-security/blob/master/security/src/main/java/io/micronaut/security/filters/SecurityFilter.java#L144).

Alternatively to security rules, [AOP Around Advice](https://docs.micronaut.io/2.5.7/guide/#aroundAdvice) could be a way of handling the case described in this issue as suggested by this comment: https://github.com/micronaut-projects/micronaut-security/discussions/649#discussioncomment-966274.
Am I right?

Thanks.

**Comment by sdelamo** [comment]
Yes, the absence of body in filters is intentional.

**Comment by sdelamo** [comment]
> Alternatively to security rules, AOP Around Advice could be a way of handling the case described in this issue as suggested by this comment: #649 (comment).

Yes, I am going to write a documentation snippet. We should have clarified this.

**Comment by sdelamo** [comment]
I am closing this issue. I have added a documentation snippet which explains that you cannot read HTTP Body from a `SecurityRule`
