### ISSUE TITLE
Improve deprecation docs for 3.0.0

### ISSUE THREAD

**Issue by ilopmar** [micronaut-projects/micronaut-security#713]
During the upgrade of micronaut-graphql to Micronaut 3.0 I needed to upgrade the security and use 3.0.0-M1 that removed a lot of deprecations and removals.
The [documentation about the breaking changes](https://micronaut-projects.github.io/micronaut-security/3.0.0-M1/guide/index.html#breaks) only explains the things that have been removed but not which classes I need to use as replacement. For doing that I used an old version of micronaut-security so I could see the javadoc of the deprecated classes and replace them with the new ones.

I think that the "breaking changes docs" should also tell the replacements to use so users know exactly what to do.

**Comment by jameskleeh** [comment]
Going to close this because its not something we typically do. We document in the javadoc in the deprecated code what should be done to upgrade. The deprecated code should be handled prior to the upgrade. Re-documenting that in breaks would take a ton of time
