### ISSUE TITLE
security.redirect.prior-to-login Does not work with urls more than 1 slash

### ISSUE THREAD

**Issue by ecmel** [micronaut-projects/micronaut-security#714]
I am using AWS Cognito Oauth2 client, if the protected url is https://host.com/task the redirect works as expected after login but if the url is https://host.com/task/1 it redirects to home page.

**Comment by jameskleeh** [comment]
@ecmel This should be resolved in the next 2.5.x and 3.0.x releases. Please let me know if it persists after

**Comment by sdelamo** [comment]
> This should be resolved in the next 2.5.x and 3.0.x releases.

@jameskleeh are you referring to core or security releases?

**Comment by ecmel** [comment]
Not fixed in micronaut 3.0.0 just FYI
