### ISSUE TITLE
JWT refresh token cookie will not be cleared on logout

### ISSUE THREAD

**Issue by logineimer** [micronaut-projects/micronaut-security#718]
### Steps to Reproduce

1. Configure your app to use JWT cookie auth
2. Login with the default `JWTCookieLoginHandler` (`/login`)
3. Logout with the default `JWTCookieClearerLogoutHandler` (`/logout`)

### Expected Behaviour

The `JWT_REFRESH_TOKEN` should be cleared.

### Actual Behaviour

The `JWT_REFRESH_TOKEN` is not cleared. I assume this is the case because in `JWTCookieClearerLogoutHandler#clearCookie()` the cookie will only be cleared if a cookie with the same name is present. However, on `/logout` the browser wont send cookies with `/oauth/access_token` domain set. Here's some screenshots:

![Screenshot 2021-07-07 at 15 07 16](https://user-images.githubusercontent.com/3143217/124765262-12b4d100-df36-11eb-9203-f57cced3e539.png)

![Screenshot 2021-07-07 at 15 07 38](https://user-images.githubusercontent.com/3143217/124765267-13e5fe00-df36-11eb-94dd-7cf717d01d0e.png)

![Screenshot 2021-07-07 at 15 09 14](https://user-images.githubusercontent.com/3143217/124765271-13e5fe00-df36-11eb-82d8-3377a33f2fc2.png)

I reckon a fix is easy as the logout handler should set a "cleared" cookie anyway, even if the cookie is not found. Is this correct?

### Environment Information

- **Operating System**: doesn't matter
- **Micronaut Version:** 3.0.0-M2 with netty server
- **JDK Version:** 16

**Comment by idleherb** [comment]
I've stumbled over the exact same issue yesterday when setting up a micronaut app with oauth. The `JWT_REFRESH_TOKEN` is restricted to the `/oauth/access_token` path, so it never reaches `/logout`.

The `JWT` token gets cleared as expected, but that doesn't help much because when the frontend makes a subsequent request to `/oauth/access_token` to refresh the access token, the refresh token cookie is sent and generates a new access token.

**Comment by hedgehogs-mind** [comment]
Experiencing the same issue with Micronaut 2.5.8.  Proposal by logineimer seems to be the best fit, as it's not possible to set multiple paths for a cookie.

**Comment by logineimer** [comment]
I wrote a workaround too but yours is more clever as you don't rewrite the whole class. I might adapt my solution to yours until my fix is hopefully getting merged and released to public. 😇

```
@Requires(property = SecurityConfigurationProperties.PREFIX + ".authentication", value = "cookie")
@Singleton
@Replaces(JwtCookieClearerLogoutHandler.class)
public class JwtCookieForceClearerLogoutHandler extends JwtCookieClearerLogoutHandler {

  public JwtCookieForceClearerLogoutHandler(
      final AccessTokenCookieConfiguration accessTokenCookieConfiguration,
      final RefreshTokenCookieConfiguration refreshTokenCookieConfiguration,
      final RedirectConfiguration redirectConfiguration) {
    super(accessTokenCookieConfiguration, refreshTokenCookieConfiguration, redirectConfiguration);
  }

  @Override
  public MutableHttpResponse<?> logout(final HttpRequest<?> request) {
    try {
      URI location = new URI(logout);
      MutableHttpResponse<?> response = HttpResponse.seeOther(location);
      clearCookie(accessTokenCookieConfiguration, response);
      if (refreshTokenCookieConfiguration != null) {
        clearCookie(refreshTokenCookieConfiguration, response);
      }
      return response;
    } catch (URISyntaxException var5) {
      return HttpResponse.serverError();
    }
  }

  private void clearCookie(final CookieConfiguration cookieConfiguration, final MutableHttpResponse<?> response) {
    final String domain = cookieConfiguration.getCookieDomain().orElse(null);
    final String path = cookieConfiguration.getCookiePath().orElse(null);
    final Cookie cookie = Cookie.of(cookieConfiguration.getCookieName(), "");
    cookie.maxAge(0).domain(domain).path(path);
    response.cookie(cookie);
  }
}
```
