### ISSUE TITLE
Support for including an audience parameter when requesting OAuth token

### ISSUE THREAD

**Issue by sturlapati-adaptive** [micronaut-projects/micronaut-security#751]
### Feature description

Auth0 expects to receive the audience parameter when requesting a token from them. This applies to following flows: AuthorizationCode, ClientCredentials, Password.

Please provide a way to specify the audience value in the oauth configuration when requesting a token.

NOTE: I already wrote the code and I can do pull request. I need some guidance on the expected tests.

thanks

**Comment by sturlapati-adaptive** [comment]
Can you please give me permission to push changes to a branch so i can create a PR?

**Comment by sdelamo** [comment]
@sturlapati-adaptive you will need to fork the repository and create a pull request from your fork.

**Comment by sdelamo** [comment]
@sturlapati-adaptive I just created a Micronaut application and used Auth0 and I did not need to supply the audience. 

I have written a guide: https://github.com/micronaut-projects/micronaut-guides/pull/500 

Can you point me what I am missing ?

**Comment by imre-kerr** [comment]
I'm not sure why it's not required in that case, but at least for Client Credentials flow the docs say it's required: https://auth0.com/docs/authorization/flows/call-your-api-using-the-client-credentials-flow#request-tokens

And the response (HTTP 403) when it's missing seems to confirm it:
```json
{"error":"access_denied","error_description":"Non-global clients are not allowed access to APIv1"}
```

**Comment by jameskleeh** [comment]
Because "audience" is not part of the standard I'm not sure we should support it explicitly, but perhaps with a map of configurable claims:

```
client-credentials:
    additional-claims:
        audience: XYZ
```

**Comment by frehov** [comment]
I've had a look at the backing code for the client credentials.
I've especially had a look at the `ClientCredentialsTokenRequestContext` which seems like it would be the most elegant place to inject those extra request parameters.

By hooking up the `ClientCredentialsTokenRequestContext` as the place to inject the extra parameters it's less vulnerable to someone overwriting parts of the secure grant map, unless they're really trying to.

This is the following change I'm proposing, and I can open a pull request with most of the relevant code if that's of interest.
```java
   private final Map<String, String> additionalRequestParams;

    @Override
    public Map<String, String> getGrant() {
        Map<String, String> grantMap = grant.toMap();
        grantMap.putAll(additionalRequestParams);
        return grantMap;
    }
```

**Comment by sturlapati-adaptive** [comment]
I agree with @jameskleeh. @frehov  i am ok with your approach and if @jameskleeh  agrees please go ahead with the PR

**Comment by sdelamo** [comment]
@frehov give me a couple of days before submitting the PR. I am working on a guide with an example of Auth0 and client credentials authentication. I want to discuss the options with everyone after I am finished with the example.

**Comment by sdelamo** [comment]
@frehov never mind I saw you submitted your PR. I will check it out.

**Comment by sdelamo** [comment]
I've written a guide which shows how to use client-credentials flow with Auth0 and Micronaut: 

https://github.com/micronaut-projects/micronaut-guides/pull/513

If you name your OAuth 2.0 client `auth0`. You may have a configuration such as:  

```yaml
micronaut:
  security:
    oauth2:
      clients:
        auth0: 
          client-id: '${OAUTH_CLIENT_ID:xxx}' 
          client-secret: '${OAUTH_CLIENT_SECRET:yyy}' 
          grant-type: 'client_credentials' 
          token:
            url: '${OAUTH_TOKEN_URL:`https://micronautguides.eu.auth0.com/oauth/token`}' 
            auth-method: 'client_secret_post' 
          client-credentials:
            service-id-regex: 'bookcatalogue|bookinventory' 
```

And you can add an extra `audience`by replacing `@Named("auth0") ClientCredentialsClient`. E.g: 

```java
package example.micronaut;

import io.micronaut.context.annotation.Replaces;
import io.micronaut.core.annotation.Nullable;
import io.micronaut.security.oauth2.client.clientcredentials.ClientCredentialsClient;
import io.micronaut.security.oauth2.client.clientcredentials.DefaultClientCredentialsClient;
import io.micronaut.security.oauth2.configuration.OauthClientConfiguration;
import io.micronaut.security.oauth2.endpoint.token.request.TokenEndpointClient;
import io.micronaut.security.oauth2.endpoint.token.request.context.ClientCredentialsTokenRequestContext;
import jakarta.inject.Named;
import jakarta.inject.Singleton;
import java.util.Map;

@Named("auth0") 
@Replaces(ClientCredentialsClient.class) 
@Singleton 
class Auth0ClientCredentials extends DefaultClientCredentialsClient {  
    private final Auth0Configuration auth0Configuration;

    Auth0ClientCredentials(@Named("auth0") OauthClientConfiguration oauthClientConfiguration,  
                                  TokenEndpointClient tokenEndpointClient,
                                  Auth0Configuration auth0Configuration) {
        super(oauthClientConfiguration, tokenEndpointClient);
        this.auth0Configuration = auth0Configuration;
    }


    @Override
    protected ClientCredentialsTokenRequestContext createTokenRequestContext(@Nullable String scope) {
        return new ClientCredentialsTokenRequestContextExtension(scope, oauthClientConfiguration, auth0Configuration);
    }

    static class ClientCredentialsTokenRequestContextExtension extends ClientCredentialsTokenRequestContext {
        private final Auth0Configuration auth0Configuration;
        public ClientCredentialsTokenRequestContextExtension(String scope,
                                                    OauthClientConfiguration clientConfiguration,
                                                    Auth0Configuration auth0Configuration) {
            super(scope, clientConfiguration);
            this.auth0Configuration = auth0Configuration;
        }
        
        @Override
        public Map<String, String> getGrant() {
            Map<String, String> m = super.getGrant();
            m.put("audience", auth0Configuration.getApiIdentifier()); 
            return m;
        }
    }
}
```
