### ISSUE TITLE
JWT Cookie "SameSite" is ignored

### ISSUE THREAD

**Issue by braeluca** [micronaut-projects/micronaut-security#755]
### Expected Behavior

The Cookie with the JWT should have the "SameSite" Property, if it is specified.

### Actual Behaviour

When specifying the "SameSite" configuration, the cookie with the JWT does not have the property.

However I had to rewrite the default "LoginController" because the HTTP-Client throw a ReadTimeoutException, with the redirect response. I had to alter the response to 200, to get client work.

I think it has to do something with the CookieConfiguration in JwtCookieLoginHandler.java:173. The Config does not contain the Properties. "SameSite" is null, despite is has been configured. 

### Steps To Reproduce

1. Create Project with Micronaut Security and JWT Cookie Authorization
3. Apply config "micronaut.security.token.jwt.cookie.cookie-same-site: strict"
4. Login with the LoginController

or run the DemoTest in the ExampleApplication

### Environment Information

- Operating System: Windows 10 Build 19042.1083
- JDK: 11.0.9

### Example Application

https://github.com/braeluca/micronaut-security-config-bug-demo

### Version

2.5.12

**Comment by braeluca** [comment]
I did some further Investigation. The configuration must exactly equals the Enum Name. However my IDE did autocomplete it to "strict" and not to "Strict".  This should be referenced in the Documentation or it should work case insensitive...

**Comment by sdelamo** [comment]
thanks for reporting @braeluca 

I have documented that value is case sensitive and added a test for this. I think value should be case insensitive. But it will require a a PR to `http-server` module.

**Comment by sdelamo** [comment]
I've documented here https://github.com/micronaut-projects/micronaut-security/pull/772

and submitted a [PR to make it case insensitive in 3.1.x of Micronaut core](https://github.com/micronaut-projects/micronaut-core/pull/6093).

**Comment by braeluca** [comment]
Thanks, for changing this behavior...
