### ISSUE TITLE
BasicAuthUtils parser does not accept an empty password

### ISSUE THREAD

**Issue by Xaseron** [micronaut-projects/micronaut-security#757]
### Expected Behavior

We are implementing a service that fetches data from SonarQube and we like to test it. As the SonarQube documentation states: 
 
> when invoking web services: just pass the token instead of your login while doing the basic authentication.

https://docs.sonarqube.org/latest/user-guide/user-token/
This also means that the password field in basic auth is empty.

We implemented a Controller with BasicAuth to test our implementation. 

The assumption in [BasicAuthUtils](https://github.com/micronaut-projects/micronaut-security/blob/1f04d99fabf2bee171e8c74887025ccea3c06f28/security/src/main/java/io/micronaut/security/authentication/BasicAuthUtils.java#L61) is wrong. After splitting the String the array can have size of 1 when the password field is empty.

### Actual Behaviour

15:06:37.791 [default-nioEventLoopGroup-1-3] DEBUG i.m.s.authentication.BasicAuthUtils - Bad format of the basic auth header - Delimiter : not found

### Version

2.5.12

**Comment by jameskleeh** [comment]
The implementation is not wrong, imo. The [RFC](https://datatracker.ietf.org/doc/html/rfc2617#section-2) makes no mention of the password being optional. It appears to me sonarqube are making use of the functionality in a way that wasn't intended.

**Comment by Xaseron** [comment]
That's true. We solved it by implementing our own `BasicAuthAuthenticationFetcher` and replacing the default one `@Replaces(BasicAuthAuthenticationFetcher::class)`.
