### ISSUE TITLE
Openid Resource Server: Authenticate with Authorization Header

### ISSUE THREAD

**Issue by juliuskrah** [micronaut-projects/micronaut-security#77]
Feature Request

When I use an access token directly in the Authorization Header with Scheme `Bearer`, I get a 401 response. 

Is there a mechanism I can configure for Resource Server?

Micronaut Security: 1.2.0
OS: Windows: 10
JDK: 11

**Comment by jameskleeh** [comment]
It's not clear to me what you're trying to do

**Comment by juliuskrah** [comment]
I want to be able to validate Oauth2 Jwt tokens in a stateless manner using the JWK_Set Url for public key validation. Similar to what Spring Security 5 does for Oauth2 resource server.

What I have done now is use a filter to validate all Jwt Bearer tokens in the Authorization header.

At the moment Micronaut Security Oauth2/OIDC support is stateful using a cookie mechanism.

**Comment by jameskleeh** [comment]
@juliuskrah That is already being done. The token returned by OpenID providers is validated against their key set URL.

**Comment by juliuskrah** [comment]
I’m aware of this. In a Microservice architecture only one service, usually the UI will handle the Login (Authorization Code Flow), other services will deal with just the Bearer Tokens.
These tokens must be validated. 

Micronaut puts these tokens in the cookie which I cannot validate in the Authorization flow.

In my case one Micronaut service works with Auth Code flow with tokens created by Micronaut stored cokies. This service communicates with another Micronaut app by sending the original Jwt from the Identity Provider in the header.
The second service (resource server) must validate the Jwt against the identity provider (no need for another login via Auth flow). This is the portion that’s missing, the verification with the public key.


I hope this clarifies stuff

**Comment by jameskleeh** [comment]
> Micronaut puts these tokens in the cookie which I cannot validate in the Authorization flow.

That is only the case if you have configured it to do so. That is not the default. You can enable the keys controller in the authorization service and have the other services use that

https://micronaut-projects.github.io/micronaut-security/1.2.x/guide/#keys

https://micronaut-projects.github.io/micronaut-security/1.2.x/guide/#jwks

**Comment by juliuskrah** [comment]
I will look at this and revert

**Comment by juliuskrah** [comment]
@jameskleeh this works. I used 

```yaml
micronaut:
  security:
    enabled: true
    token:
      jwt:
        enabled: true
        signatures:
          jwks:
            keycloak:
              url: 'https://<domain>:<port>/auth/realms/<realm>/protocol/openid-connect/certs'
```

I wasn't interested in the keys endpoint. 

Question: Any suggestion on how to customize the `getName()` to use `preferred_username` instead of `Subject`?

Question: Also any suggestion on how to extract the roles or scopes to participate in the `@Secured({"ROLE_ADMIN", "ROLE_X"})` flow

**Comment by jameskleeh** [comment]
Please ask questions in Gitter

**Comment by juliuskrah** [comment]
Copy that
