### ISSUE TITLE
support usage of jakarta annotations for micronaut-security

### ISSUE THREAD

**Issue by frehov** [micronaut-projects/micronaut-security#774]
### Feature description

Hi,

I'd like to request that the jakarta annotations for RolesAllowed, PermitAll and DenyAll be included in the annotation mappers pressent in the security-annotation package for micronaut.
They should be the same as their javax equivalents, but in a new namespace.

We hit this gotcha when trying to use `@RolesAllowed` from the jakarta annotations library and our authentication passed directly through ignoring the annotation.

**Comment by graemerocher** [comment]
good idea, seems fairly simple to address, would you like to send a PR?

**Comment by frehov** [comment]
I can probably take a stab at it.
Is there anything that I should keep in mind for the PR?

**Comment by graemerocher** [comment]
the way we have done this before is subclass the `javax` mappers and overrride the annotation name however that does require changing them from a `TypedAnnotationMapper` to a `NamedAnnotationMapper` but at least avoids some duplication

**Comment by frehov** [comment]
alright, let's see if I have this correct.

By changing to a NamedAnnotationMapper like the following
```java
@Internal
public class DenyAllAnnotationMapper implements NamedAnnotationMapper {
    @Override
    public String getName() {
        return "javax.annotation.security.DenyAll";
    }

    @Override
    public List<AnnotationValue<?>> map(AnnotationValue<Annotation> annotation, VisitorContext visitorContext) {
        List<AnnotationValue<?>> annotationValues = new ArrayList<>(1);
        annotationValues.add(
                AnnotationValue.builder(Secured.class)
                        .value("denyAll()")
                        .build()
        );
        return annotationValues;
    }
}
```

and then subclassing the next one like this
```java
@Internal
public class JakartaDenyAllAnnotationMapper extends DenyAllAnnotationMapper {
    @Override
    public String getName() {
        return "jakarta.annotation.security.DenyAll";
    }
}
```

would solve it?

**Comment by graemerocher** [comment]
yes, the new one would need to be added into the `META-INF/services` config as well
