### ISSUE TITLE
Refactor AuthenticationResponse

### ISSUE THREAD

**Issue by jameskleeh** [micronaut-projects/micronaut-security#81]
Currently the login controller makes assumptions that a successful authentication response is a UserDetails and a failed response is an AuthenticationFailed. We should remove that assumption and change the response interface to allow for handling of both types of responses. UserDetails should be an implementation detail instead of a requirement

**Comment by zonaut** [comment]
As this is in the same context I would also like to point out the following. 
When trying to authenticate against the login controller if always returns an application/json response. This can be seen when posting empty values in the form which fails the Validation on UsernamePasswordCredentials.

Normally this is not a problem but when using a form post I would expect the response to be that form with the errors, which is not happening. The only solution I see for now is to implement that logic myself and change the login end point to that new path and handle the errors there. 

Maybe there is an easier solution, if there is let me know.
