### ISSUE TITLE
[JWT] Ability to modify default "/login" response to include more fields.

### ISSUE THREAD

**Issue by jaybcee** [micronaut-projects/micronaut-security#812]
### Feature description

Currently, in the implementation of the [AuthenticationProvider](https://github.com/micronaut-projects/micronaut-security/blob/master/security/src/main/java/io/micronaut/security/authentication/AuthenticationProvider.java) interface an `AuthenticationResponse` is returned. This response resembles the following
```
{
    "username": "basile",
    "roles": [
        "CLIENT"
    ],
    "access_token": "eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJiYXNpbGUiLCJuYmYiOjE2MzQ0MTQ2NzYsInJvbGVzIjpbIkNMSUVOVCJdLCJpc3MiOiJzb3RlcmlhIiwiZXhwIjoxNjM0NDE4Mjc2LCJpYXQiOjE2MzQ0MTQ2NzYsImVtYWlsIjoiYmFzaWxlQGJpZy5jb20ifQ.ID1BtQwV1yFDcWJAaxbIkOucKbB9crKSlNM8iPE-Q5M",
    "refresh_token": "eyJhbGciOiJIUzI1NiJ9.NWVkNWI3OWMtMzEyNi00N2JiLWFiMjQtODI3MGUxMWZkODJm.GWjET1jBlvI2wOXozu2Utcizgt2617sA_EeBwUh-Ni8",
    "token_type": "Bearer",
    "expires_in": 3600
}
```

The authentication response signature I'm using is the following https://github.com/micronaut-projects/micronaut-security/blob/master/security/src/main/java/io/micronaut/security/authentication/AuthenticationResponse.java#L98

The third parameter is a Map<K,V> of values. The values that I pass to this parameter are ONLY found within the JWT token, not the body of the payload itself. I don't see any clear way in the documentation to return them in the JSON.

![image](https://user-images.githubusercontent.com/44372106/137635802-32d1a785-e362-4714-af49-0c5a752f0164.png)

As you can see in the image, the key "email" is encoded in the JWT, but not in the JSON response above. How can I get the email in the response.

Thanks in advance and apologies if this the wrong forum, however it seems fundamental enough that I think others could benefit.

**Comment by jaybcee** [comment]
> * BearerTokenRenderer

I apologize, I believe you are right! The class names are a bit confusing however. I have seen the same issue here https://github.com/micronaut-projects/micronaut-core/issues/712 and there appears to be a solution. I believe this should be documented. I will try to contribute once I have figured it out. Thanks for your response.

**Comment by averri** [comment]
Hi @sdelamo, how to retrieve the user object that has been created in the login action, which happens in the class that implements the `AuthenticationProvider` interface? It's not clear to me how to pass custom data from the `AuthenticationProvider` to the final stage that renders the response to the client (`BearerTokenRenderer` in this case).

**Comment by averri** [comment]
I have discovered how to pass data from `AuthenticationProvider` to the final stage, we need to set the data in the `attributes` property of the `AuthenticationResponse`.
