### ISSUE TITLE
Make JWT Cookie login/logout redirect optional

### ISSUE THREAD

**Issue by alejandropg** [micronaut-projects/micronaut-security#844]
### Feature description

Hi @sdelamo 

as you told me I open a new issue to "reactivate" the subject. But take into account that this is a duplication/continuation of #96 and #97 

The suggested feature is to make optional the JWT Cookie login/logout redirect.

The use case is that sometimes (for me is rather always 😅) you develop a REST API that is consumed by a Web/JavaScript client. In this scenario I think that is very appropriate to use the JWT Cookie login/logout because with the secure and server-side is most difficult that a malicious user could manipulate the token.

In this scenario is not good the redirection after login, because the login consumer is just a JavaScript client.

You commented in issue #96 that is able to extend the class `JwtCookieLoginHandler` and change this behavior. I did it and works pretty well.

But my suggestion is that, right now Micronaut Security has some redirections configuration properties like:

- `micronaut.security.redirect.unauthorized.enabled`
- `micronaut.security.redirect.refresh.enabled`
- `micronaut.security.redirect.forbidden.enabled`

So maybe could have sense to have a property something like `micronaut.security.redirect.enabled` (default value true) to turn on or off the login and logout redirection. 

What do you think?

Thanks a lot!

**Comment by sdelamo** [comment]
I think `micronaut.security.redirect.enabled` with a default to `true` works. Would you be willing to contribute a PR ?

**Comment by alejandropg** [comment]
I could try 😅
Let me some time, at least one week (you know, I have to do it in my free time). If in the end, I can't, I will notify you.

**Comment by sdelamo** [comment]
If you cannot do it, it is fine. I will try to included it in 3.2. or 3.3 of Micronaut Security.

**Comment by sdelamo** [comment]
@alejandropg check linked PR. I think it fulfils your requirements.

**Comment by alejandropg** [comment]
Hi @sdelamo 

First of all, really thanks a lot because that should have been my job, but between work and the Christmas vacations it has been impossible for me to get down to it.

I checked the code and it looks reeeeally good, also build and test the branch in my local and it looks like work like a charm 👌

Thanks!

**Comment by alejandropg** [comment]
Continues in #885
