### ISSUE TITLE
Authenticate user programatically (Security JWT)

### ISSUE THREAD

**Issue by mrcoto** [micronaut-projects/micronaut-security#85]
Hello everyone!

Is there a way to authenticate a user programatically (manually)?? I'm using `micronaut-security-jwt` dependency

For example in Spring Boot you can do something like:

```java
UsernamePasswordAuthenticationToken authReq = new UsernamePasswordAuthenticationToken(user, pass);
Authentication auth = authManager.authenticate(authReq);
SecurityContext sc = SecurityContextHolder.getContext();
securityContext.setAuthentication(auth);
```
But, there is no SecurityContextHolder in Micronaut.

Thanks in advance!

**Comment by ashwini-desai** [comment]
[Here](https://micronaut-projects.github.io/micronaut-security/1.2.x/guide/#authenticationProviders) are the details in the documentation. 
Similar to how we have to implement ```UserDetailsService``` that sets the returned ```UserDetails``` in ```SecurityContext``` in Spring Boot, you have to provide an implementation of ```AuthenticationProvider``` and return a ```UserDetails``` object.

**Comment by alvarosanchez** [comment]
This would be what you would be looking for:

```java
Authenticator authenticator = null; //@Inject it
AuthenticationRequest<?,?> authenticationRequest = new UsernamePasswordCredentials("user", "pass");
Flowable.fromPublisher(authenticator.authenticate(authenticationRequest))
        .doOnNext(authenticationResponse -> {
            if (authenticationResponse.isAuthenticated()) {
                UserDetails userDetails = (UserDetails) authenticationResponse;
                Authentication authentication = new AuthenticationUserDetailsAdapter(userDetails, "roles");
                ServerRequestContext.currentRequest().ifPresent(request -> request.setAttribute(HttpAttributes.PRINCIPAL, authentication));
            }
        });
```
