### ISSUE TITLE
Token propagation problem

### ISSUE THREAD

**Issue by rkimaoui** [micronaut-projects/micronaut-security#86]
Token propagation is not working when calling a client oustide of controller.

Example: when calling my client "userClient" on application bootstrap.
```groovy
onApplicationEvent(ServerStartupEvent event) {
log.debug "USERS:" + userClient.list()
}
```

**Comment by goeh** [comment]
I don't think that use-case is supported. How would Micronaut get access to a token if the call was not initiated from an inbound HTTP request? You don't have a token available at server startup.
I guess you need to get/create the token manually for the user you want use with userClient.
