### ISSUE TITLE
Open Id end session url from provider is not used

### ISSUE THREAD

**Issue by neoneo** [micronaut-projects/micronaut-security#87]
Our OpenID provider supports end session, and Micronaut also sees this when fetching from `/.well-known/openid-configuration`. `OpenIdProviderMetadata#getEndSessionEndpoint` returns the end_session_endpoint. 

However, Micronaut seems to ignore this when resolving the `EndSessionEndPoint` in `EndSessionEndpointResolver`. When no bean is provided that implements that interface, the resolve method only checks if the issuer is one of the default ones.

As far as I can see, additional to the default providers, a simple `EndSessionEndpoint` implementation could be created if `OpenIdProviderMetadata#getEndSessionEndpoint` is not null. Is there a reason this is not supported?

Additional steps taken to work around this:
- Create a bean with the proper qualifier and use `OpenIdProviderMetadata`. However, the `OpenIdProviderMetadata` is not known until right before resolving the bean. I'm not sure if it's possible to inject `OpenIdProviderMetadata` into my bean. If so, I'd like to hear it.
- Config `micronaut.security.oauth2.clients.*.openid.end-session.url`, where * contains the name of our provider. This was not picked up automatically.
- Combination of these two: a bean that accepts the config as a constructor argument. This works, but is a little bit less than ideal since the end session endpoint has to be added to config.

**Comment by jameskleeh** [comment]
@neoneo The issue is that there is no standard about how to construct the request to the URL

You can register your own named `EndSessionEndpoint` bean to allow the functionality to work

**Comment by jameskleeh** [comment]
Closing this due to a lack of feedback
