### ISSUE TITLE
JwksSignature validation depends on "alg"

### ISSUE THREAD

**Issue by jvrhenen** [micronaut-projects/micronaut-security#89]
The current implementation of the JwksSignature depends on the "alg" attribute of the JSON Web Key (JWK) .
According to the documentation this attribute is optional (https://tools.ietf.org/html/draft-ietf-jose-json-web-key-41#section-4.4).

This implementation cannot handle some openID services, for example Azure AD.
https://login.microsoftonline.com/common/discovery/keys

"When used with JWS or JWE, the "kid" value is used to match a JWS or JWE "kid" Header Parameter value." 
https://tools.ietf.org/html/draft-ietf-jose-json-web-key-41#section-4.5

**Comment by alvarosanchez** [comment]
Same as #90
