### ISSUE TITLE
Oauth2 - bearer token validation via token 3rd introspection endpoint

### ISSUE THREAD

**Issue by svishnyakoff** [micronaut-projects/micronaut-security#91]
I believe this request is pretty much similar to https://github.com/micronaut-projects/micronaut-security/issues/3 though here I will give high-level idea about how configuration and implementation might look like

The basic idea is the following: 

1. Service with protected resources receives a request with a bearer token
2. To validate token and obtain associated context, server calls authorization's service token introspection endpoint.
3. It is the responsibility of auth service to verify a token and provide associated token information like user name, roles, and other information.
4. Based on authorization service response, server authorizes (or not) a request

More details can be found in RFC https://tools.ietf.org/html/rfc7662 and basically a request is to implement an authentication mechanism described in this RFC.

### Implementation:
Oauth configuration are extended to allow configuration of token introspection endpoint
1. `micronaut.security.token.oauth2.bearer.introspection.url` - defines url of token introspection endpoint
2.  `micronaut.security.token.oauth2.bearer.introspection.tokenParam` - allows to customize token parameter when passing it to introspection endpoint
3. `micronaut.security.token.oauth2.bearer.introspection.tokenHintsParameters` - allows to pass additional helper parameters along the token (Allowed by RFC)
4. `micronaut.security.token.oauth2.bearer.introspection.credentials.clientId` - if token introspection endpoint secured, this  will be login
5. `micronaut.security.token.oauth2.bearer.introspection.credentials.clientId` - if token introspection endpoint secured, this  will be password

New validator `ClientCredentialsTokenValidator` is added to the security-oauth2 module. The validator will call introspection endpoint to verify token.

Although token introspection response is standardized by https://tools.ietf.org/html/rfc7662, there are many examples when introspection endpoints might not follow the standard https://stackoverflow.com/questions/12296017/how-to-validate-an-oauth-2-0-access-token-for-a-resource-server. Out of the box only response described in rfc7662 is supported, but devs should be able to override the default behaviour by implementing related introspection response handler interface.

**Comment by jameskleeh** [comment]
So I don't think we need separate config for this. The existing Oauth2 client config can handle any additional configuration necessary. The OauthClientConfigurationProperties already has introspection properties and clientid/secret.

Are you planning on implementing this with a filter? How will token expiration be handled?

**Comment by svishnyakoff** [comment]
I agree, using existing OauthClientConfigurationProperties is better than introducing duplicating config that will serve the same purpose.
 
You can get a general idea of implementation from here https://github.com/svishnyakoff/micronaut-security/commit/5d0a2e49916ac56cd0491906328d8cf015a9fde3#diff-8642ec23ea2721ea48918389d5d2642f. 

Regarding token expiration handling, it is the responsibility of authorization service, so we will just rely on it.

**Comment by jameskleeh** [comment]
So I don't think we should be validating the token for every request given the performance implications. We should retrieve the token if it doesn't exist and cache it. The cache would expire automatically if we know the expiration time. If the request with the token fails because the token is no longer valid for any reason, we should be referring to the originally cached refresh token to get a new access token and then retrying the original request.

**Comment by svishnyakoff** [comment]
Caching of introspection response also has a security implication that should be evaluated. RFC considers caching as an option but highlights the idea that a choice of performance vs security depends on the application needs.

I am not against introducing caching for token validation because performance concerns many application, but still, there are those where security might be more important. So at least there should be a configuration that would let opt-out to avoid caching.

Additionally, there probably should be several strategies for cache TTL. Cache invalidation interval also has security implication, so I would let user configure expiration interval (still control under the hood it won't exceed value from "exp" parameter)

Quote from RFC:
> Since a protected resource MAY cache the response of the
   introspection endpoint, designers of an OAuth 2.0 system using this
   protocol MUST consider the performance and security trade-offs
   inherent in caching security information such as this.  A less
   aggressive cache with a short timeout will provide the protected
   resource with more up-to-date information (due to it needing to query
   the introspection endpoint more often) at the cost of increased
   network traffic and load on the introspection endpoint.  A more
   aggressive cache with a longer duration will minimize network traffic
   and load on the introspection endpoint, but at the risk of stale
   information about the token.  For example, the token may be revoked
   while the protected resource is relying on the value of the cached
   response to make authorization decisions.  This creates a window
   during which a revoked token could be used at the protected resource.
   Consequently, an acceptable cache validity duration needs to be
   carefully considered given the concerns and sensitivities of the
   protected resource being accessed and the likelihood of a token being
   revoked or invalidated in the interim period.  Highly sensitive
   environments can opt to disable caching entirely on the protected
   resource to eliminate the risk of stale cached information entirely,
   again at the cost of increased network traffic and server load.  If
   the response contains the "exp" parameter (expiration), the response
   MUST NOT be cached beyond the time indicated therein.

**Comment by svishnyakoff** [comment]
If ignore cache and cache related configurations for now, here is how client credential configuration might look like
```yml
micronaut:
  security:
    enabled: true
    oauth2:
      enabled: true
      clients:
        authService:
          client-id: <<my client id>>
          client-secret: <<my client secret>>
          grantType: CLIENT_CREDENTIALS
          introspection:
            url: http://localhost/token/introspection
            authMethod: CLIENT_SECRET_BASIC
```

**Comment by jameskleeh** [comment]
We would need `micronaut.security.oauth2.clients.*.client-credentials.url-patterns` to denote which URLs should be filtered.

What are
```
tokenParam: token
            tokenHintsParameters:
              token_type_hint: bearer
```
used for?

**Comment by jameskleeh** [comment]
Thanks for the caching information. I think we should default to caching until the token is expired because then we are allowing the server to determine what is an acceptable default caching period.

**Comment by svishnyakoff** [comment]
> What are
> 
> tokenParam: token
>             tokenHintsParameters:
>               token_type_hint: bearer
> used for?

It controls the body that will be sent to introspection endpoint. tokenHintsParameters is documented in RFC. Regarding the `tokenParam` so far RFC states it should be `token`, but for example, our organization I am working in uses a different name `access_token` and basically google, github and other top companies started to use introspection endpoint before it was clearly documented in RFC so they likely might different name for token parameter.

@jameskleeh yes we will also need `url-patterns` config but that is mostly related to client and how http client will receive security token from the authorization service. For the server authorization, we don't need `url-patterns` specified cause we already have `@Secured` responsible for marking endpoints requiring authorization check.

I prefer to dedicate this issue, just for server part, how server should verify oauth2 token using authorization token. Anything related to http client configuration I would prefer to do in scope separte issue. With such approach it would just be easier to have a discussion and start earlier working on actual implementation. What do you think?

**Comment by nbrugger-tgm** [comment]
I would vote for this issue to be reopened.
Just because the config keys exist doesn't fulfil "bearer token validation via token 3rd introspection endpoint" when the config keys have no effect

> It is possible to configure the introspection endpoint URL for OAuth 2.0 and OpenID providers, however Micronaut currently does not use this configuration in any way.

Does not sound like "we completed bearer token validation via 3rd party introspection endpoint"

**Comment by nbrugger-tgm** [comment]
@jameskleeh why is this ticket closed?
