### ISSUE TITLE
RFC 7636: Proof Key for Code Exchange (PKCE)

### ISSUE THREAD

**Issue by strmik** [micronaut-projects/micronaut-security#951]
### Feature description

PKCE ([RFC 7636](https://tools.ietf.org/html/rfc7636)) is an extension to the [Authorization Code flow](https://oauth.net/2/grant-types/authorization-code/) to prevent CSRF and authorization code injection attacks.

It's an optional extension for OAuth2.0 for confidential clients. Draft of OAuth 2.1 suggest that PKCE is [mandatory](https://oauth.net/2.1/) (including confidential clients).

**Comment by graemerocher** [comment]
@burtbeckwith next time you have engineering cycles please take this on

**Comment by graemerocher** [comment]
@sdelamo add to the roadmap

**Comment by sdelamo** [comment]
PCKE is typically used in platforms (e.g. mobile phone native apps) where redirect URLs are not available. Not sure what we can do on our side but let's consider it.

**Comment by strmik** [comment]
I don't think this is limited to platforms, as OAuth2.1 draft makes that mandatory for confidential clients (like Micronaut)... If I understood this right, the actual change should be quite small. It's about generating a random number, hashing it and send the hash with the request for authorization code. Then add the random number to the request for tokens...
